# -- Autogenerated by tools/ports_analyse.py --
# -- 2023-05-11 20:15:59 --

ports_info = {
  "items": {
    "2048.sh": "2048.zip",
    "2048/": "2048.zip",
    "Abes Adventure.sh": "abes_adventure.zip",
    "abes_adventure/": "abes_adventure.zip",
    "Abu Simbel Profanation Deluxe.sh": "profadeluxe.zip",
    "Abuse.sh": "abuse.zip",
    "Abuse/": "abuse.zip",
    "alephone/": [
      "alephone-marathon.zip",
      "alephone-marathon2.zip",
      "alephone-marathoninfinity.zip"
    ],
    "Alien vs Predator.sh": "avp.zip",
    "AM2R.sh": "am2r.zip",
    "am2r/": "am2r.zip",
    "Anarch.sh": "anarch.zip",
    "anarch/": "anarch.zip",
    "Augustus.sh": "augustus.zip",
    "augustus/": "augustus.zip",
    "avp/": "avp.zip",
    "Axiom Verge.sh": "axiom.verge.zip",
    "axiom-verge/": "axiom.verge.zip",
    "Bermuda Syndrome.sh": "bermuda_syndrome.zip",
    "bermuda/": "bermuda_syndrome.zip",
    "BillyFrontier.sh": "billyfrontier.zip",
    "billyfrontier/": "billyfrontier.zip",
    "Blake Stone - Aliens of Gold.sh": "bstone-aog.zip",
    "Blake Stone - Planet Strike.sh": "bstone-ps.zip",
    "Blobby Volley 2.sh": "blobby.volley2.zip",
    "blobbyvolley2/": "blobby.volley2.zip",
    "Blobwars.sh": "blobwars.zip",
    "blobwars/": "blobwars.zip",
    "Block Attack.sh": "block.attack.zip",
    "blockattack/": "block.attack.zip",
    "Blockout 2.sh": "blockout2.zip",
    "blockout2/": "blockout2.zip",
    "Blood.sh": "blood.zip",
    "Blood/": "blood.zip",
    "Blues Brothers Jukebox Adventure.sh": "bbja.zip",
    "Blues Brothers.sh": "blues.brothers.zip",
    "bluesbrothers/": "blues.brothers.zip",
    "bstone-aog/": "bstone-aog.zip",
    "bstone-ps/": "bstone-ps.zip",
    "Bugdom.sh": "bugdom.zip",
    "bugdom/": "bugdom.zip",
    "C-Dogs.sh": "c-dogs.zip",
    "Cannonball.sh": "cannonball.zip",
    "cannonball/": "cannonball.zip",
    "Cave Story-evo.sh": "cave.story-evo.zip",
    "Cave Story.sh": "cave.story.zip",
    "cavestory/": "cave.story.zip",
    "cdogs/": "c-dogs.zip",
    "Celeste.sh": "celeste.zip",
    "celeste/": "celeste.zip",
    "cgenius/": "commander.genius.zip",
    "Commander Genius.sh": "commander.genius.zip",
    "CorsixTH.sh": "corsixth.zip",
    "CorsixTH/": "corsixth.zip",
    "cosmo-engine/": "cosmo-engine.zip",
    "Cosmos Cosmic Adventure.sh": "cosmo-engine.zip",
    "CroMagRally.sh": "cromagrally.zip",
    "cromagrally/": "cromagrally.zip",
    "Dave Gnukem.sh": "davegnukem.zip",
    "davegnukem/": "davegnukem.zip",
    "Der Clou.sh": "derclou.zip",
    "derclou/": "derclou.zip",
    "devilution/": "devilutionx.zip",
    "Devilutionx.sh": "devilutionx.zip",
    "Dinothawr.sh": "dinothawr.zip",
    "dinothawr/": "dinothawr.zip",
    "DiverDown.sh": "diverdown.zip",
    "diverdown/": "diverdown.zip",
    "Doom 3.sh": "doom3.zip",
    "doom3/": "doom3.zip",
    "Duke Nukem 3D.sh": "duke.nukem.3d.zip",
    "DungeonRush.sh": "dungeonrush.zip",
    "dungeonrush/": "dungeonrush.zip",
    "Eity.sh": "eity.zip",
    "eity/": "eity.zip",
    "Enigma.sh": "enigma.zip",
    "enigma/": "enigma.zip",
    "Exhumed.sh": "exhumed.zip",
    "Exhumed/": "exhumed.zip",
    "Exult-keyring.sh": "exult.zip",
    "Exult-nokeyring.sh": "exult.zip",
    "exult/": "exult.zip",
    "F2bgl.sh": "fade_to_black.zip",
    "f2bgl/": "fade_to_black.zip",
    "Falling Time.sh": "falling_time.zip",
    "falling_time/": "falling_time.zip",
    "Fallout 1.sh": "fallout1.zip",
    "Fallout 2.sh": "fallout2.zip",
    "fallout1/": "fallout1.zip",
    "fallout2/": "fallout2.zip",
    "Fheroes2.sh": "fheroes2.zip",
    "fheroes2/": "fheroes2.zip",
    "Flare Engine.sh": "flare.zip",
    "flare/": "flare.zip",
    "Freedom Planet.sh": "freedom.planet.zip",
    "freedomplanet/": "freedom.planet.zip",
    "Freedroid.sh": "freedroid.zip",
    "freedroid/": "freedroid.zip",
    "Freegemas.sh": "freegemas.zip",
    "freegemas/": "freegemas.zip",
    "FreeSerf.sh": "freeserf.zip",
    "freeserf/": "freeserf.zip",
    "GemRB.sh": "gemrb.zip",
    "gemrb/": "gemrb.zip",
    "Gigalomania.sh": "gigalomania.zip",
    "gigalomania/": "gigalomania.zip",
    "Gloom - Zombie Massacre.sh": "zgloom.zip",
    "Gloom 3.sh": "zgloom.zip",
    "Gloom Deluxe.sh": "zgloom.zip",
    "Gloom.sh": "zgloom.zip",
    "Half-Life 2.sh": "half-life.2.zip",
    "Half-Life Blue Shift.sh": "half-life.zip",
    "Half-Life Opposing Forces.sh": "half-life.zip",
    "Half-Life.sh": "half-life.zip",
    "Half-Life/": "half-life.zip",
    "halflife2/": "half-life.2.zip",
    "hcl/": "hydra.castle.labyrinth.zip",
    "Heart of Darkness.sh": "heart.of.darkness.zip",
    "Hex-A-Hop.sh": "hex-a-hop.zip",
    "hex-a-hop/": "hex-a-hop.zip",
    "Hexen 2 - Portal of Praevus.sh": "hexen2.zip",
    "Hexen 2.sh": "hexen2.zip",
    "hexen2/": "hexen2.zip",
    "Hijinx.sh": "hijinx.zip",
    "hijinx/": "hijinx.zip",
    "Hocoslamfy.sh": "hocoslamfy.zip",
    "hocoslamfy/": "hocoslamfy.zip",
    "hode/": "heart.of.darkness.zip",
    "Hurrican.sh": "hurrican.zip",
    "hurrican/": "hurrican.zip",
    "Hydra Castle Labyrinth.sh": "hydra.castle.labyrinth.zip",
    "Iconoclasts.sh": "iconoclasts.zip",
    "iconoclasts/": "iconoclasts.zip",
    "IIChantra P.E.A.R.sh": "iichantra_pear.zip",
    "iichantra_pear/": "iichantra_pear.zip",
    "Invaders.sh": "invaders.zip",
    "Invaders/": "invaders.zip",
    "iortcw/": "iortcw.zip",
    "JediAcademy/": "jediacademy.zip",
    "JediOutcast/": "jedioutcast.zip",
    "jukeboxadventure/": "bbja.zip",
    "Maldita Castilla.sh": "maldita.castilla.zip",
    "MalditaCastilla/": "maldita.castilla.zip",
    "Marathon 2.sh": "alephone-marathon2.zip",
    "Marathon Infinity.sh": "alephone-marathoninfinity.zip",
    "Marathon.sh": "alephone-marathon.zip",
    "Meritous.sh": "meritous.zip",
    "meritous/": "meritous.zip",
    "MightyMike.sh": "mightymike.zip",
    "mightymike/": "mightymike.zip",
    "Mirror Magic.sh": "mirrormagic.zip",
    "mirrormagic/": "mirrormagic.zip",
    "Moonlight.sh": "moonlight.zip",
    "moonlight/": "moonlight.zip",
    "Mr. Boom.sh": "mr.boom.zip",
    "mrboom/": "mr.boom.zip",
    "Multris.sh": "multris.zip",
    "multris/": "multris.zip",
    "NAM.sh": "nam.zip",
    "Nanosaur.sh": "nanosaur.zip",
    "nanosaur/": "nanosaur.zip",
    "Neverball.sh": "neverball.zip",
    "neverball/": "neverball.zip",
    "Neverputt.sh": "neverball.zip",
    "nKaruga.sh": "nkaruga.zip",
    "nkaruga/": "nkaruga.zip",
    "Nonny.sh": "nonny.zip",
    "nonny/": "nonny.zip",
    "nxengine-evo/": "cave.story-evo.zip",
    "Oddworld Abes Exoddus.sh": "oddworld.zip",
    "Oddworld Abes Oddysee.sh": "oddworld.zip",
    "OpenBlok.sh": "openblok.zip",
    "openblok/": "openblok.zip",
    "Openclaw.sh": "openclaw.zip",
    "openclaw/": "openclaw.zip",
    "OpenFodder.sh": "openfodder.zip",
    "openfodder/": "openfodder.zip",
    "OpenJazz.sh": "openjazz.zip",
    "openjazz/": "openjazz.zip",
    "Openomf.sh": "openomf.zip",
    "openomf/": "openomf.zip",
    "OpenRCT2.sh": "openrct2.zip",
    "openrct2/": "openrct2.zip",
    "Openttd.sh": "openttd.zip",
    "openttd/": "openttd.zip",
    "OpenTyrian.sh": "opentyrian.zip",
    "opentyrian/": "opentyrian.zip",
    "openxcom/": "openxcom.zip",
    "OpenXcomEX.sh": "openxcom.zip",
    "OttoMatic.sh": "ottomatic.zip",
    "ottomatic/": "ottomatic.zip",
    "Owlboy.sh": "owlboy.zip",
    "owlboy/": "owlboy.zip",
    "Pekka Kana 2.sh": "pekka-kana-2.zip",
    "pekka-kana-2/": "pekka-kana-2.zip",
    "Powder.sh": "powder.zip",
    "powder/": "powder.zip",
    "Prehistorik 2.sh": "prehistorik.2.zip",
    "prehistorik2/": "prehistorik.2.zip",
    "profadeluxe/": "profadeluxe.zip",
    "Quake 2.sh": "quake.2.zip",
    "Quake 3.sh": "quake3.zip",
    "Quake.sh": "quake.zip",
    "quake/": "quake.zip",
    "quake2/": "quake.2.zip",
    "quake3/": "quake3.zip",
    "RAWGL.sh": "rawgl.zip",
    "rawgl/": "rawgl.zip",
    "Redneck Rampage Rides Again.sh": "redneck.rampage.rides.again.zip",
    "Redneck Rampage.sh": "redneck.rampage.zip",
    "rednukem-dn3d-atomic/": "duke.nukem.3d.zip",
    "rednukem-NAM/": "nam.zip",
    "rednukem-redneck1/": "redneck.rampage.zip",
    "rednukem-redneck2/": "redneck.rampage.rides.again.zip",
    "rednukem-WWII/": "world.war.ii.gi.zip",
    "relive/": "oddworld.zip",
    "REminiscence.sh": "reminiscence.zip",
    "reminiscence/": "reminiscence.zip",
    "Return to Castle Wolfenstein.sh": "iortcw.zip",
    "Ri-Li.sh": "ri_li.zip",
    "ri_li/": "ri_li.zip",
    "Rick Dangerous.sh": "rick.dangerous.zip",
    "RigelEngine.sh": "rigelengine.zip",
    "RigelEngine/": "rigelengine.zip",
    "Rlvm.sh": "rlvm.zip",
    "rlvm/": "rlvm.zip",
    "Rocks n Diamonds.sh": "rocksndiamonds.zip",
    "rocksndiamonds/": "rocksndiamonds.zip",
    "ROTT.sh": "rott.zip",
    "rott/": "rott.zip",
    "RVGL.sh": "rvgl.zip",
    "rvgl/": "rvgl.zip",
    "SDLPoP.sh": "sdlpop.zip",
    "sdlpop/": "sdlpop.zip",
    "Shadow Warrior.sh": "shadow.warrior.zip",
    "shadow-warrior/": "shadow.warrior.zip",
    "Shipwreck.sh": "shipwreck.zip",
    "shipwreck/": "shipwreck.zip",
    "Shovel Knight.sh": "shovel.knight.zip",
    "shovelknight/": "shovel.knight.zip",
    "Simple Sokoban.sh": "simplesokoban.zip",
    "simplesok/": "simplesokoban.zip",
    "Skijump3.sh": "skijump3.zip",
    "skijump3/": "skijump3.zip",
    "sm64.sh": "sm64.zip",
    "sm64/": "sm64.zip",
    "smw/": "super.mario.war.zip",
    "Sonic 1.sh": "sonic.1.zip",
    "Sonic 2.sh": "sonic.2.zip",
    "Sonic CD.sh": "sonic.cd.zip",
    "Sonic Mania.sh": "sonic.mania.zip",
    "Sonic Robo Blast 2 Kart.sh": "srb2kart.zip",
    "sonic1/": "sonic.1.zip",
    "sonic2/": "sonic.2.zip",
    "soniccd/": "sonic.cd.zip",
    "sonicmania/": "sonic.mania.zip",
    "SorR.sh": "sorr.zip",
    "sorr/": "sorr.zip",
    "Space Cadet Pinball.sh": "space.cadet.pinball.zip",
    "spacecadetpinball/": "space.cadet.pinball.zip",
    "Spelunky.sh": "spelunky.zip",
    "spelunky/": "spelunky.zip",
    "SRB2.sh": "srb2.zip",
    "SRB2/": "srb2.zip",
    "srb2kart/": "srb2kart.zip",
    "Star Wars Jedi Knight - Jedi Academy.sh": "jediacademy.zip",
    "Star Wars Jedi Knight II - Jedi Outcast.sh": "jedioutcast.zip",
    "Starcatcher.sh": "starcatcher.zip",
    "starcatcher/": "starcatcher.zip",
    "StardewValley.sh": "stardewvalley.zip",
    "stardewvalley/": "stardewvalley.zip",
    "SteelAssault.sh": "steelassault.zip",
    "steelassault/": "steelassault.zip",
    "Super Mario War.sh": "super.mario.war.zip",
    "SuperTux.sh": "supertux.zip",
    "supertux/": "supertux.zip",
    "Tamatool.sh": "tamatool.zip",
    "tamatool/": "tamatool.zip",
    "Thermomorph.sh": "thermomorph.zip",
    "thermomorph/": "thermomorph.zip",
    "Tile World (Chip's Challenge).sh": "tileworld.zip",
    "Tile World (Natural Theme Mod).sh": "tileworld.zip",
    "tileworld/": "tileworld.zip",
    "Timespinner.sh": "timespinner.zip",
    "timespinner/": "timespinner.zip",
    "Tiny Crate.sh": "tiny-crate.zip",
    "tiny-crate/": "tiny-crate.zip",
    "Titan Tactics.sh": "titan_tactics.zip",
    "titan_tactics/": "titan_tactics.zip",
    "TMNTShreddersRevenge.sh": "tmntsr.zip",
    "tmntsr/": "tmntsr.zip",
    "Tomb Raider 1.sh": "tomb.raider.1.zip",
    "tombraider1/": "tomb.raider.1.zip",
    "Ultimatetapankaikki.sh": "ultimatetapankaikki.zip",
    "ultimatetapankaikki/": "ultimatetapankaikki.zip",
    "Undertale.sh": "undertale.zip",
    "undertale/": "undertale.zip",
    "Upo.sh": "upo.zip",
    "upo/": "upo.zip",
    "UQM.sh": "uqm.zip",
    "UQM/": "uqm.zip",
    "VanillaRA.sh": "vanillara.zip",
    "vanillara/": "vanillara.zip",
    "VanillaTD.sh": "vanillatd.zip",
    "vanillatd/": "vanillatd.zip",
    "VCMI.sh": "vcmi.zip",
    "vcmi/": "vcmi.zip",
    "VVVVVV.sh": "vvvvvv.zip",
    "VVVVVV/": "vvvvvv.zip",
    "Wetspot2.sh": "wetspot2.zip",
    "wetspot2/": "wetspot2.zip",
    "Wordle SDL.sh": "wordlesdl.zip",
    "wordlesdl/": "wordlesdl.zip",
    "World War II GI.sh": "world.war.ii.gi.zip",
    "Worship Vector.sh": "worship_vector.zip",
    "worship/": "worship_vector.zip",
    "xrick/": "rick.dangerous.zip",
    "zgloom/": "zgloom.zip"
  },
  "md5": {
    "00ec80092bf65bfe11a328988763df5c": "Devilutionx.sh",
    "010d585bf7c627f24b4e7ddc08645846": "Undertale.sh",
    "01d3ca06bbca3ea03bdbce04f66085a6": "Exult-keyring.sh",
    "027075e05bcec6262dc172219cfc8bb5": "Tomb Raider 1.sh",
    "0297702410c84cedc015a7e867e35278": "Hijinx.sh",
    "0465c358bd13491e0d31f4b4c7e96683": "Moonlight.sh",
    "048530e24c19dee31587960b08a574f4": "Blake Stone - Aliens of Gold.sh",
    "05a3571b35bb87732d83a660051470bf": "Redneck Rampage Rides Again.sh",
    "07a9a99e6aa605b721996674721040f4": "Blake Stone - Planet Strike.sh",
    "0831d6de587df3e0c1171c6596b8e0cb": "Tamatool.sh",
    "095bbf628e26d2fdb73131f8163be79a": "Timespinner.sh",
    "0980a8cf0eaeab4f24dde8c19cf891de": "RAWGL.sh",
    "099147c91369ac3b252e68a155a14919": "Cannonball.sh",
    "0a187d9bc8ff58bc1c3d376971668d83": "Hexen 2 - Portal of Praevus.sh",
    "0a81b0be1a3dee0450d9a1b85b72f921": "Star Wars Jedi Knight II - Jedi Outcast.sh",
    "0b3d64d21efef93688b480db2cccece7": "Openclaw.sh",
    "0ba6efd891cddb8e1403525956434488": "Doom 3.sh",
    "0bc3b50d1f2388f49f2d29c112f6621b": "Starcatcher.sh",
    "0c6a6da2affbfcb8367d49b96b6319db": "Freedroid.sh",
    "0c9c70b432625bb88a667273e95e152f": "Oddworld Abes Exoddus.sh",
    "0d4e65f5f9c29969d50220eafe88f181": "Titan Tactics.sh",
    "0ecffc8f920e10cc8f6b43a9b85ce679": "VVVVVV.sh",
    "1068cff3f8c926a85f649dc895b681c0": "Mr. Boom.sh",
    "120bddd6ea7ee6f0d92879ae8a452542": "Iconoclasts.sh",
    "121e68ff5b417d8d900e20b414a78507": "Moonlight.sh",
    "12d755de17496ccdcf9857b36eccd869": "Invaders.sh",
    "12fb1cb8ccc54d06f23bade0ffb06424": "Space Cadet Pinball.sh",
    "13877253638d1241e077cdbb4934bd15": "Cave Story.sh",
    "1458a82898ab99bcfd845f39a635035b": "Meritous.sh",
    "150c3150d991e9504c26eb949bea2e70": "RVGL.sh",
    "1597834fdd1803e3310ef314cb02af5c": "Redneck Rampage.sh",
    "15fca94eccea29af01f6d282c70c9dcd": "Openttd.sh",
    "164ed4e668acfc20730d66ba783fc096": "RAWGL.sh",
    "16647f52968cdcb8558141d0c7cbc887": "Neverputt.sh",
    "173d8d9dc6e6631ea87af95cbb0b4db2": "Redneck Rampage Rides Again.sh",
    "17a9ce40a8cf970c566dd4b1f6a8146c": "Quake.sh",
    "17c5d359af995f7f837dfb36e037d69d": "Blobby Volley 2.sh",
    "182ab337b7e4c16265e3b59b842bdfa1": "Fallout 1.sh",
    "18ef1627436565c28c8a92e38a0541f2": "Sonic Mania.sh",
    "1914abf44427b7d2e016adf5aca21d97": "Return to Castle Wolfenstein.sh",
    "1a1077bdf87251701326ff90cfc70e5c": "SteelAssault.sh",
    "1be6de868d1f0fb7eaa514dd0a838d3c": "C-Dogs.sh",
    "1e4479b941ed109f300a32f112330f75": "VCMI.sh",
    "1f8e07c76f1dd47f2dadfb17c74b34fe": "Star Wars Jedi Knight - Jedi Academy.sh",
    "2088f76934af92638a1e25220e44524d": "Bermuda Syndrome.sh",
    "20e787e2debcdde4d0395af8a7f2dbd8": "Cosmos Cosmic Adventure.sh",
    "214fdd1fbf3bb2cfd590b304e6a2a65b": "Block Attack.sh",
    "225d25af37bdb24247bcfab8f55d96e4": "Hurrican.sh",
    "236fa09f6bc386bd2e0954dc95a08a93": "Sonic 2.sh",
    "23f8172d912cf3ab2fb248c26eafcba1": "Invaders.sh",
    "241580ee987ca45f17106036f000024a": "Freedom Planet.sh",
    "2415fbc3eca5817b1a56141a40bd73b1": "SteelAssault.sh",
    "245f060c1567896fcc420bdf1a80ceaa": "OttoMatic.sh",
    "2483b063fb0d93779d64785f2f3e1cb9": "nKaruga.sh",
    "258f3722b15ee2b2432e28c733bbff6c": "Gloom.sh",
    "26815ae937a8606c02a17c127356af65": "OpenRCT2.sh",
    "269d257c909c9784278639f965ef6209": "Thermomorph.sh",
    "274be74c882fae351833ffa306ec3e01": "SuperTux.sh",
    "279b951324ff075043351c50d7feb9b1": "VanillaTD.sh",
    "27c2591eeee6e7e4628b7104e36d6831": "Blake Stone - Aliens of Gold.sh",
    "27c665acba9a82d0fdeae2beeff92a30": "SDLPoP.sh",
    "28f5e977efb43caef46b8ecc92851d93": "Exhumed.sh",
    "296a21c21d8eeb4720ec3d4ed140d739": "Super Mario War.sh",
    "29dde6014c638b2c0051198424043bb7": "Pekka Kana 2.sh",
    "2aa6980e9c3fa108a02cc41d02231c20": "2048.sh",
    "2d94f7606358431d5f6e93a34ee33a33": "Space Cadet Pinball.sh",
    "2da5346ff2fa079ca9de37d6a08dd989": "Blobby Volley 2.sh",
    "2e121cdfbba99d09c9ccbcdb3ba88bc6": "Hocoslamfy.sh",
    "2e9e0c4e722df54cbba0d54e8fe3ec20": "Blake Stone - Aliens of Gold.sh",
    "2f2d175c154e85e200a1290bc1d29a35": "Exhumed.sh",
    "2fd463f8346edfec16bea5f9c0367823": "Fheroes2.sh",
    "3077ff590283ca43e502493bf8caceb1": "Sonic 1.sh",
    "31d7051c16c2047f939bd75c4fa45c3d": "CorsixTH.sh",
    "328fc2e6cf3e9fb179588e7e740830bd": "Owlboy.sh",
    "34e16abb0891bf8edb212ca4e138a132": "OpenJazz.sh",
    "350ce8d1337cd79a440d80ea97948c63": "Blake Stone - Aliens of Gold.sh",
    "35b78140ce53436b0248549057c1abcf": "StardewValley.sh",
    "35ea4eccfc757fc392e35b6e16db4714": "Duke Nukem 3D.sh",
    "3622abb928db942e533562435736fa9d": "Openclaw.sh",
    "378cedce7bf9c50f0620cb15ded134c5": "RVGL.sh",
    "37bcf5475a29f8608ffc81fde7161fa0": "VVVVVV.sh",
    "381a6cc7a368c4b626d25c6d69cd4cc3": "Quake 3.sh",
    "3a80ae6235eceb41c11541ab743f94fe": "Moonlight.sh",
    "3a8af7d0f26e892247faabcdff86dd73": "SDLPoP.sh",
    "3abfdc093e4cc86ed7e5f8947c7373a0": "Doom 3.sh",
    "3b245e807db88a9a1de3046bf5cc6770": "Blues Brothers.sh",
    "3b7f6328af7796cd7cb6742e97d1895e": "Openclaw.sh",
    "3d694a2ce81e0fdda759809973d14097": "Rocks n Diamonds.sh",
    "3d6bdbaf44e3fb15bf313477186bd21a": "Neverball.sh",
    "4043bad532b4f3d4ed1bf22133be3f12": "Doom 3.sh",
    "4068cf0a3f0e498e100a2eaf215afce2": "Gigalomania.sh",
    "40fe75e4f7a4cda241732f116b92ec4a": "Blake Stone - Planet Strike.sh",
    "4105cedeb4d3d7523682207acbc307b8": "Blues Brothers.sh",
    "41427ffaef59dee0c51ee910fc420630": "Owlboy.sh",
    "41dab8ebce4fd24d9712e69f88bd6041": "Sonic Robo Blast 2 Kart.sh",
    "42109701d1b864d66f37ccd68a8af5e9": "Super Mario War.sh",
    "4258ab05272a3a5af168168c5b342eb9": "Quake.sh",
    "445a1c683c4d48a53d6da4e872e2a7ea": "Redneck Rampage.sh",
    "44eb3109a0942a480251586dbc0655b1": "NAM.sh",
    "4780584e115a81830350f8c26741dac1": "Gloom 3.sh",
    "4788cfdcfb67445473f4105f1ead1e2c": "Maldita Castilla.sh",
    "47a2bdef8fbd936d89b698a5fb810912": "Skijump3.sh",
    "49e2b6c8c499df821142a6664f453862": "Redneck Rampage Rides Again.sh",
    "4a36314a2501bfcf48d0bbe08d4e4883": "Openclaw.sh",
    "4abab5c652dca45a0973565cd13c3f7f": "SRB2.sh",
    "4c29727ada31427d3aadead5e85dd50f": "Freedom Planet.sh",
    "4ca37fe1b50d178375851c18c081876c": "Openclaw.sh",
    "4d242b59d741026abea9a54f7cfec248": "Oddworld Abes Oddysee.sh",
    "4e0a3449cd13412cb1d0f0916623479a": "Heart of Darkness.sh",
    "4ebeb0ed5f9f0d8ba2cbbf1dc4eb8feb": "Cave Story-evo.sh",
    "508d91d0fa58b741403102e94dadd5bf": "RAWGL.sh",
    "50b5151f6ad3a4f56ef029c3dd050c0c": "Hurrican.sh",
    "50fdff16f49cd829d449d6d748a5ec1e": "Moonlight.sh",
    "526bd880bc2799f9a4ee6be57519883c": "Invaders.sh",
    "53384805ef0ee47ffabf98848f4ba26a": "Exult-nokeyring.sh",
    "533ea36696125b7fe2e8b8d4b25c253e": "Eity.sh",
    "5467966dd3912be32b72e7cd27871d4f": "Half-Life.sh",
    "5467b3bbadfe31d53279143c019c6df7": "Shovel Knight.sh",
    "54b8c0c15e0bf8cd59137531414b30bf": "Spelunky.sh",
    "54eab6dec3177d465e40210309e44ba0": "OpenTyrian.sh",
    "552ef0aeb69c69ca18551ce965c98133": "C-Dogs.sh",
    "5572a9360fb0f2b4f8ec81e70f10d111": "SorR.sh",
    "563f2ed018c8e7b0ebc943bbc2ff136d": "Commander Genius.sh",
    "57218164ce9ae338956efc34c9dc64c6": "Iconoclasts.sh",
    "578bc1f8124a480d7b744a1d6a4468f9": "Blake Stone - Aliens of Gold.sh",
    "5825d1dac0885e900c25fc6c5314e5f9": "Gloom - Zombie Massacre.sh",
    "5becc0d9139e6b41e1e4844da673dd71": "World War II GI.sh",
    "5cef57b412c391c9f7d4839bacd43fa6": "Wetspot2.sh",
    "5e20d29c0caaba95b3466cf4e0a08251": "Quake 2.sh",
    "5e9ae04d22d82f3294a7d89757bfa4ff": "Mirror Magic.sh",
    "5ea75dd71884a5d5d2c83eed1627ccc1": "MightyMike.sh",
    "5eab1ea2edd5b29196b3add5a9b6758d": "Cave Story-evo.sh",
    "5ece63fecc9e02132e879d960a1d5f32": "Marathon.sh",
    "5ee90a6240662cfd870a89fa13c1cd56": "Abes Adventure.sh",
    "5f6168a0d00581ec68ba371d5b2e84b5": "Bermuda Syndrome.sh",
    "5f8de08363b407e0bea82c85547fdd95": "Openomf.sh",
    "60831f62519d9395abb50e43aa8a96b5": "Blues Brothers Jukebox Adventure.sh",
    "61aa7de58863fe29c9d10678791127a4": "Tile World (Natural Theme Mod).sh",
    "62666ecc4a45eb55d0ec09bc0d23043b": "Sonic CD.sh",
    "636b109af403b8a9f10ba49d1bb8d577": "CorsixTH.sh",
    "653ab3a59a406392903bcd8b0b1cc106": "RVGL.sh",
    "660b0e9db3dcca6ac03e65ef9e1616f1": "Timespinner.sh",
    "668e41872495565315a313283a7128b1": "StardewValley.sh",
    "670bae747117fa4f729c53e0e3c511ec": "Skijump3.sh",
    "67445aedf7413b53a641c893d3d2b957": "Shadow Warrior.sh",
    "67fe17a8b00ba539e6c5412f1631d94c": "Blues Brothers Jukebox Adventure.sh",
    "6cd8cdcf96bf7178fe28fdbe6a3d1a6d": "Blues Brothers Jukebox Adventure.sh",
    "6d4ab072d061656c5b6f91638af86317": "Flare Engine.sh",
    "6ea1903017f054d207aa10ae0e8e097e": "Rick Dangerous.sh",
    "6ee5b23091a51d97bd2d59298f416c7b": "Quake 2.sh",
    "6f657b6d14b68828e2a9b4533b884075": "Ri-Li.sh",
    "6f814ff945c5c44151239ac147d04d95": "Shadow Warrior.sh",
    "7057b555341b20c23c895d6c1c8cd841": "Shovel Knight.sh",
    "717c57f9067a87cd63922dc25f1b9363": "Commander Genius.sh",
    "722e3a646736044a16b7d336b2c6299c": "Marathon.sh",
    "72526b4b6b00767e3a23e19c21127626": "Marathon 2.sh",
    "72a3c5207e7824e354e899ec274d4cde": "C-Dogs.sh",
    "737012ee312aece49325616087bb70fb": "RigelEngine.sh",
    "73ef4e03c56bcb8d2985fc2c88dc21ad": "Mr. Boom.sh",
    "742c4da6f673f9d5830af37c0b087bbf": "Return to Castle Wolfenstein.sh",
    "750063d3b25632ff4d0416df1e8b4c67": "ROTT.sh",
    "7645bc8d75286bb9d0122d094f7179dc": "Shadow Warrior.sh",
    "766cff280a8b038942621ad903e9b35d": "RigelEngine.sh",
    "76919f174519367cf7863773a449cb43": "Spelunky.sh",
    "769e9a0dbf335b480573b5f902ac5fc2": "Hexen 2.sh",
    "775886d9b322a69c6e7c0e4c3f6c9f37": "Axiom Verge.sh",
    "777641a8a2f266d57c405d5d12cf568d": "Cave Story-evo.sh",
    "77cef0a1a0731a2d23e6043176bb3ec6": "Sonic Mania.sh",
    "7912b02e7974e54df2eccabd073cf904": "Blake Stone - Aliens of Gold.sh",
    "7a504fa36b5bd08c35d969c107bc88e3": "F2bgl.sh",
    "7b5ae74f78671ea6acd3290911fe7022": "Fallout 1.sh",
    "7ca110d91fe347a52871b7e4b2665640": "Star Wars Jedi Knight - Jedi Academy.sh",
    "7cb599e93b65348d7e29c0e28c41766e": "Iconoclasts.sh",
    "7ec5961ee3339e31407567f9eacf1aa8": "Blood.sh",
    "80209362fa23aba4a2834f1c66286fe6": "Openclaw.sh",
    "81385916e98f5a7049fdec56362d67f8": "Hydra Castle Labyrinth.sh",
    "81a2363bde36fe9fa1ce25c2fd5c4b32": "F2bgl.sh",
    "822e9cf9ef4fcf5e337c9239691f537c": "Star Wars Jedi Knight - Jedi Academy.sh",
    "8373399de5fda0e74b60244ed04d6c94": "Fallout 2.sh",
    "8442b1b5356d36a5dc4bd27799e4fa84": "IIChantra P.E.A.R.sh",
    "84817051865f5dcd352338a683cc13c1": "Blake Stone - Planet Strike.sh",
    "8492d2f59a0defbcead97f43c286a29b": "Redneck Rampage.sh",
    "84e2760c05d297aafde80bb3947f4167": "CroMagRally.sh",
    "84f1447854f2a9a7ce2dd22616dcc08c": "FreeSerf.sh",
    "852caa2a2aea1e2ac6702505d8128eab": "Fallout 2.sh",
    "865c1b97122a6815b0fb851f6d741af4": "Blake Stone - Planet Strike.sh",
    "865e54c91a35087f8de6f3176fa0ced9": "Fheroes2.sh",
    "86b7099e1882ac1ff2f63d3df015e4ff": "Rocks n Diamonds.sh",
    "87872f13aa7a8de51d981780bb92b0f9": "Abuse.sh",
    "87f75805099c373f921a1a47d217a67a": "OpenBlok.sh",
    "88dfb0c2a995598c64b5c60b1e740594": "Blobby Volley 2.sh",
    "88e23e69464597e324f96ee44b1b0fb4": "Block Attack.sh",
    "894ca37c8203f26ef517fca3f9392863": "Exult-nokeyring.sh",
    "896be085d7205b3f8ea66bafc864d8a8": "REminiscence.sh",
    "897c937938e39e75618188faade5bf32": "Block Attack.sh",
    "8a14d47ff2af769b3d872df8c56510e4": "CorsixTH.sh",
    "8a5eaeef96b1f8691640cc40e3b19d48": "AM2R.sh",
    "8aab07bdd7c58a630edd90e51e69d6ef": "OpenJazz.sh",
    "8b7f960968082a32da966498ed2b1ab5": "OpenXcomEX.sh",
    "8b894f051fef37732563829cdecfa860": "Ultimatetapankaikki.sh",
    "8b96cc97f48963ce85944b707280626a": "Fallout 1.sh",
    "8d01e320091071dd7315747d9b7606a4": "IIChantra P.E.A.R.sh",
    "8d65bd1c92d17fa0caf1dc951670730e": "Sonic 1.sh",
    "8e61b3812a16b99a5ede8584949eee43": "Duke Nukem 3D.sh",
    "8fa16118438c0722e149a7a75ed5753a": "Blake Stone - Aliens of Gold.sh",
    "8fdf9f8e45be0b6887b59c32fe1afc21": "Wordle SDL.sh",
    "9262fc5cf4fdc7d2da6523b3ecc93e5b": "REminiscence.sh",
    "92cd199d66af5489d2e86688c23af69d": "AM2R.sh",
    "932a26cc4e4fe491d064b31a8b9d64f6": "Marathon Infinity.sh",
    "95caeb116ddc00851629dcd289569f1a": "Duke Nukem 3D.sh",
    "9634bb24bb9ba889fe347ab4247cc538": "OpenTyrian.sh",
    "974a511c92843373cbb08cdeb7d1e52c": "Abu Simbel Profanation Deluxe.sh",
    "97f4964e38b8f6e1fc4c0ebe9c582c83": "Prehistorik 2.sh",
    "981b536db6bc86482fa72e5c344eabe8": "Undertale.sh",
    "98b6594c394d39f2234890ad2ddc2530": "Return to Castle Wolfenstein.sh",
    "99899db668228670aadf9ba27f46eec9": "Prehistorik 2.sh",
    "9b49e7b3045bf92b6d5748a6ebad56e5": "Augustus.sh",
    "9b672a1c111b17305341389dd43f98ce": "Blake Stone - Planet Strike.sh",
    "9bfd94c7140ea5ce2f01c1514516db74": "Spelunky.sh",
    "9d17fbfeaf40f26f2e449e7781c2f19d": "Wordle SDL.sh",
    "9d42ec40afb30b464fd9df02953418cf": "Blake Stone - Planet Strike.sh",
    "9db56365a4837f64aa98d43f51e18299": "Abuse.sh",
    "9dde625b856e374685b4cb5ba4120882": "F2bgl.sh",
    "9df866f21b102155765a68f69244dfa7": "Sonic 1.sh",
    "9f247210a44da7142a80164f263c974b": "World War II GI.sh",
    "9f7ef7e1d55ea6beda42c0ff74915057": "Moonlight.sh",
    "a142586766d22c288f7b2ca29434424b": "VanillaRA.sh",
    "a21185b88b97fc549f3f64a0f268ac2f": "Alien vs Predator.sh",
    "a263e558201087849e875c8ce9cabd5b": "nKaruga.sh",
    "a29e886fb488e6292e0c139d9450d316": "Shipwreck.sh",
    "a4014537b17041468b0115b9d92f7687": "Dinothawr.sh",
    "a4850e17508d75616a82273462ebd282": "OpenJazz.sh",
    "a580a33c91f2a64ecbf2519165d52368": "Heart of Darkness.sh",
    "a5d81cd19e8707d55ab87d4e30b3c112": "Bugdom.sh",
    "a6204c64e06a9da937c2033b00abf2a3": "Nanosaur.sh",
    "a68fb09fe7990daef97fe0e8df2c88b6": "Openomf.sh",
    "a95756728e13d20facc66316d44fc659": "C-Dogs.sh",
    "a9b361c2db8568d7c923cc8c844cc67b": "SorR.sh",
    "a9d31069be2708090b78cf0643742657": "Abuse.sh",
    "ab9cade517491e255e198d4b9f04d521": "Exhumed.sh",
    "acc60f3627487c01795f99316ff0d3e8": "OpenJazz.sh",
    "ace44a893f8d735a1c8f4e07329edb28": "Devilutionx.sh",
    "ad06d32197502a93191eb432063bf471": "BillyFrontier.sh",
    "ad60d62c3e383e9770e976f2ba1c127b": "Upo.sh",
    "ae45e3c2d873c9ba25e0c3f3e62e4930": "Half-Life.sh",
    "afb506b256fff3860a8b66f429aa32d6": "Sonic 2.sh",
    "b1a14590079e7b01969fb8e345730144": "Heart of Darkness.sh",
    "b29b634dc82a5b655d9d2a254b33668e": "C-Dogs.sh",
    "b2eb4a40716f357a30ccf0ab0d9a4e51": "Exult-keyring.sh",
    "b328c48b7c58adb4ae5726fa606c12d3": "VanillaRA.sh",
    "b625cd1669073737183b1a3b33c4bd95": "AM2R.sh",
    "b66362d80d8b780fa423aa0326dc2cd2": "Marathon 2.sh",
    "b7b37e25a80714d1750dd4bccdd3d376": "Commander Genius.sh",
    "ba06794d388d2abd480c38a5e44fb27a": "World War II GI.sh",
    "ba3386cf5481eb216f28611ba6763dc9": "Tile World (Chip's Challenge).sh",
    "bbc865ad69fa0d03b7623719c9443276": "Prehistorik 2.sh",
    "bed4ae7412680ed85ccd90f7a2dd061b": "DiverDown.sh",
    "bf145c87baccdd275d90ad029f579119": "Exult-keyring.sh",
    "bf64520eaae95439a0d237ed9624b7f9": "Hex-A-Hop.sh",
    "c094b4dd32e0e415e5d1aa509c2c7462": "Rlvm.sh",
    "c0df68829382ab7d0bce9645988543a4": "Maldita Castilla.sh",
    "c189a6adfb5792882b922ab53e3c61a8": "Marathon Infinity.sh",
    "c242b4b062811ebbf67e0acf85cef1be": "Heart of Darkness.sh",
    "c2849aecd1a50fb97814a69942228602": "Powder.sh",
    "c2996677e3153b9165759f545429e38d": "Rick Dangerous.sh",
    "c2aba8dfd541c718e3929fcdd55eb27e": "Undertale.sh",
    "c35b2d0b637cb7b4f23f379fe3287896": "Blake Stone - Aliens of Gold.sh",
    "c5568b7de9863fd840b181b2f39be048": "NAM.sh",
    "c60e5517549a5b3e11bfce17295ce735": "SteelAssault.sh",
    "c7199a2f594c2a0623eb477635f0d350": "RVGL.sh",
    "c8540824458b78911ba80db270b77595": "Multris.sh",
    "c8d658d9a26360618ffbb524bddc3148": "Star Wars Jedi Knight - Jedi Academy.sh",
    "c8e7e5ef61f47d06b530ad1219d63c67": "OpenJazz.sh",
    "cb31da7934177b440f389e80d985f5ce": "Sonic 2.sh",
    "cb4e5973e7d9b1954d6b3295150c36dc": "Nonny.sh",
    "ccd690b006b4427f8119468543430d42": "REminiscence.sh",
    "cd277506a530e618c7ac5fa0d9674473": "Hexen 2 - Portal of Praevus.sh",
    "cd88246198e52ed62b2a41e3d7c194d9": "Tomb Raider 1.sh",
    "ce5e3fc899d977eef0ac05adf4555ff8": "Owlboy.sh",
    "cf49021c64d935f20b2b2c3b412de178": "Super Mario War.sh",
    "cf9d44ffcb090a8414640f8755dea264": "Star Wars Jedi Knight II - Jedi Outcast.sh",
    "d0219cb4efffcf1492623520c7650ae8": "Blake Stone - Planet Strike.sh",
    "d0fd0e5e367d93435609acb9f62cf8d4": "Exult-nokeyring.sh",
    "d10a403186a4d29a4929127c0925860c": "VanillaTD.sh",
    "d232b3172ecd6825d7ca7eb299912f03": "Blake Stone - Planet Strike.sh",
    "d239df815ca1ca1b25633b2e4ccf1954": "Blobwars.sh",
    "d36bda4aeec1c1f22caf0a20366dc201": "Hexen 2.sh",
    "d43c7c00b59dec7b116bfd2cb53419a2": "Blake Stone - Planet Strike.sh",
    "d470552d47d1afe68e2ed575ae063d50": "DungeonRush.sh",
    "d4cc7b7e56b007d5e85397005bf9f999": "OpenFodder.sh",
    "d4f03898d572fb81b68d2739231d13c0": "Iconoclasts.sh",
    "d5d160f49dd167c3f25e709db90f879f": "Blood.sh",
    "d615bb6c949f9f3e3b4cb5318df52df0": "Dinothawr.sh",
    "d763aedf87dc65321b954222d2b59375": "Quake 2.sh",
    "d77e2d8931534e3efea8daba953dffba": "Der Clou.sh",
    "d7dcf1118d9b3ed84c788398683b3d38": "Commander Genius.sh",
    "d92a98cc2ea2e157cb6d5fa2a13733b8": "Blockout 2.sh",
    "d970060b5f8447a8f92501af55f118c0": "VanillaTD.sh",
    "d9989b04a9721dfe7b62f9b50b0e1dbf": "Tiny Crate.sh",
    "dad15d660474f59e0dbbe302bb1bc707": "RAWGL.sh",
    "db1be98b4e257774ee0ac7a146c03211": "OpenJazz.sh",
    "dd14a814b3c64889acbb2e3fa14901d5": "Enigma.sh",
    "dd3a1d3d35c058b4139f8c3172ec262c": "Openomf.sh",
    "dd48af495545b6f0da4ba13db4ed9808": "Quake 3.sh",
    "de99b33f0afd943fe755d0b87780ef9b": "SDLPoP.sh",
    "dfba2d3e16e12dac94e5ad793be59cde": "Openclaw.sh",
    "dfe6d0234822dc8cec0cb0fcb031d893": "Timespinner.sh",
    "e0876ad40b9a7268c65bd06342032920": "OpenJazz.sh",
    "e0e42dea164ebaeedbd7f748c2ead1e8": "Worship Vector.sh",
    "e1acb77332005a5eb4494927a87bb3b4": "OpenJazz.sh",
    "e1eba2f4e26f59e4c71acfba653ed708": "Anarch.sh",
    "e2263658c232b1dc294c9e48bbf51d32": "Quake.sh",
    "e277354e2983c7f3aa8daf8a1329326f": "Star Wars Jedi Knight II - Jedi Outcast.sh",
    "e3388bbc0b001886921b8c46bbc760b2": "VanillaRA.sh",
    "e39be0dfe33e8be952e88229ed9f26b8": "Simple Sokoban.sh",
    "e3f1ba07723d1e63a88c62d6dd404380": "Marathon 2.sh",
    "e4118d1b5668adf016435e783b1daddd": "Hurrican.sh",
    "e50250514230f2a2712289d0931cc320": "NAM.sh",
    "e56e29755e3924323f545893543c5c15": "2048.sh",
    "e69a271e2f04d18fc26b7d3b88148fd0": "Moonlight.sh",
    "e7b1b6e616179df4e38714e4d9d87974": "Skijump3.sh",
    "e89b0e6b365803cc077bc147679b2529": "Cave Story.sh",
    "e8a25ffcd18d21467d3501dd11914730": "Cannonball.sh",
    "ea428f6223f5bed5b172f2dc4fdfa0fe": "Wordle SDL.sh",
    "ea44ad50bf683955914ba0b0e94233cc": "Blues Brothers Jukebox Adventure.sh",
    "ea5aff23f79639e1af1bb45e046ef8a1": "Freegemas.sh",
    "eb3d0523c645758ed0b34265bed35cf5": "Commander Genius.sh",
    "ec544f23ca886209f289c9dd12e99d01": "Blake Stone - Planet Strike.sh",
    "edd065956eb6eb1d460b7e646aa84ef6": "Blues Brothers.sh",
    "edee4b80a9fa15355605aa40ebc4e8cc": "Gloom Deluxe.sh",
    "ee24495628c5ea972e767f2b02f2eae7": "SorR.sh",
    "ee529136ceda74b39be164172a5935a4": "Dave Gnukem.sh",
    "ee9d6e5fe5ba5c5c24ca35ef612580ac": "nKaruga.sh",
    "f005524ddc201856679b4ffb0fea0100": "Maldita Castilla.sh",
    "f04f47c0596789fe2f05ce0a367942e9": "Shovel Knight.sh",
    "f04fa6a4c2b507488aa8bc1f9867e921": "Hurrican.sh",
    "f2880b043abbb39897d8f1d3bccb2994": "Hurrican.sh",
    "f5e3a7d31a86db3049cd608f26dfae78": "Enigma.sh",
    "f6fb582985b9dfef745b5f2812f34a33": "Star Wars Jedi Knight II - Jedi Outcast.sh",
    "f71e743bf03b1f03af7a2b620cb1405b": "Sonic CD.sh",
    "f723f0b7673db2d5bba18ae27af86d63": "Quake 3.sh",
    "f7422c9c03bc3f76ba50329b9d45b209": "UQM.sh",
    "f91b1e7528c9d97d85a785575cfdd2b3": "OpenTyrian.sh",
    "faf6ca06438d8661f96a58c6fac463c5": "Marathon.sh",
    "fb3e93fa2c8f1ca27836f2ebed9ae889": "ROTT.sh",
    "fb8107037d22d4af828c82047f21b9a5": "Hydra Castle Labyrinth.sh",
    "fbb61a40be7e8f8100a12d4f12073ffd": "Marathon Infinity.sh",
    "fc2476dfd9465c728c614a1987d85951": "Blake Stone - Aliens of Gold.sh",
    "fd0c734a99b9378a35b0387d3c39f732": "Freedom Planet.sh",
    "fd1f4f809f4652528b52a85ed6eed4c6": "GemRB.sh",
    "fdc2f43f9b270c427302fe43b23801ec": "VanillaRA.sh",
    "fdfaa1963fee9b735bca7a10e2f235d9": "Falling Time.sh"
  },
  "ports": {
    "2048.zip": {
      "file": "2048/2048.port.json",
      "items": ["2048.sh", "2048/"],
      "name": "2048.zip"
    },
    "abes_adventure.zip": {
      "file": "abes_adventure/abes_adventure.port.json",
      "items": ["Abes Adventure.sh", "abes_adventure/"],
      "name": "abes_adventure.zip"
    },
    "abuse.zip": {
      "file": "Abuse/abuse.port.json",
      "items": ["Abuse/", "Abuse.sh"],
      "name": "abuse.zip"
    },
    "alephone-marathon.zip": {
      "file": "alephone/alephone-marathon.port.json",
      "items": ["alephone/", "Marathon.sh"],
      "name": "alephone-marathon.zip"
    },
    "alephone-marathon2.zip": {
      "file": "alephone/alephone-marathon2.port.json",
      "items": ["alephone/", "Marathon 2.sh"],
      "name": "alephone-marathon2.zip"
    },
    "alephone-marathoninfinity.zip": {
      "file": "alephone/alephone-marathoninfinity.port.json",
      "items": ["alephone/", "Marathon Infinity.sh"],
      "name": "alephone-marathoninfinity.zip"
    },
    "am2r.zip": {
      "file": "am2r/am2r.port.json",
      "items": ["AM2R.sh", "am2r/"],
      "name": "am2r.zip"
    },
    "anarch.zip": {
      "file": "anarch/anarch.port.json",
      "items": ["anarch/", "Anarch.sh"],
      "name": "anarch.zip"
    },
    "augustus.zip": {
      "file": "augustus/augustus.port.json",
      "items": ["Augustus.sh", "augustus/"],
      "name": "augustus.zip"
    },
    "avp.zip": {
      "file": "avp/avp.port.json",
      "items": ["Alien vs Predator.sh", "avp/"],
      "name": "avp.zip"
    },
    "axiom.verge.zip": {
      "file": "axiom-verge/axiom.verge.port.json",
      "items": ["axiom-verge/", "Axiom Verge.sh"],
      "name": "axiom.verge.zip"
    },
    "bbja.zip": {
      "file": "jukeboxadventure/bbja.port.json",
      "items": ["Blues Brothers Jukebox Adventure.sh", "jukeboxadventure/"],
      "name": "bbja.zip"
    },
    "bermuda_syndrome.zip": {
      "file": "bermuda/bermuda_syndrome.port.json",
      "items": ["bermuda/", "Bermuda Syndrome.sh"],
      "name": "bermuda_syndrome.zip"
    },
    "billyfrontier.zip": {
      "file": "billyfrontier/billyfrontier.port.json",
      "items": ["BillyFrontier.sh", "billyfrontier/"],
      "name": "billyfrontier.zip"
    },
    "blobby.volley2.zip": {
      "file": "blobbyvolley2/blobby.volley2.port.json",
      "items": ["Blobby Volley 2.sh", "blobbyvolley2/"],
      "name": "blobby.volley2.zip"
    },
    "blobwars.zip": {
      "file": "blobwars/blobwars.port.json",
      "items": ["Blobwars.sh", "blobwars/"],
      "name": "blobwars.zip"
    },
    "block.attack.zip": {
      "file": "blockattack/block.attack.port.json",
      "items": ["Block Attack.sh", "blockattack/"],
      "name": "block.attack.zip"
    },
    "blockout2.zip": {
      "file": "blockout2/blockout2.port.json",
      "items": ["Blockout 2.sh", "blockout2/"],
      "name": "blockout2.zip"
    },
    "blood.zip": {
      "file": "Blood/blood.port.json",
      "items": ["Blood.sh", "Blood/"],
      "name": "blood.zip"
    },
    "blues.brothers.zip": {
      "file": "bluesbrothers/blues.brothers.port.json",
      "items": ["Blues Brothers.sh", "bluesbrothers/"],
      "name": "blues.brothers.zip"
    },
    "bstone-aog.zip": {
      "file": "bstone-aog/bstone-aog.port.json",
      "items": ["Blake Stone - Aliens of Gold.sh", "bstone-aog/"],
      "name": "bstone-aog.zip"
    },
    "bstone-ps.zip": {
      "file": "bstone-ps/bstone-ps.port.json",
      "items": ["Blake Stone - Planet Strike.sh", "bstone-ps/"],
      "name": "bstone-ps.zip"
    },
    "bugdom.zip": {
      "file": "bugdom/bugdom.port.json",
      "items": ["Bugdom.sh", "bugdom/"],
      "name": "bugdom.zip"
    },
    "c-dogs.zip": {
      "file": "cdogs/c-dogs.port.json",
      "items": ["C-Dogs.sh", "cdogs/"],
      "name": "c-dogs.zip"
    },
    "cannonball.zip": {
      "file": "cannonball/cannonball.port.json",
      "items": ["Cannonball.sh", "cannonball/"],
      "name": "cannonball.zip"
    },
    "cave.story-evo.zip": {
      "file": "nxengine-evo/cave.story-evo.port.json",
      "items": ["Cave Story-evo.sh", "nxengine-evo/"],
      "name": "cave.story-evo.zip"
    },
    "cave.story.zip": {
      "file": "cavestory/cave.story.port.json",
      "items": ["Cave Story.sh", "cavestory/"],
      "name": "cave.story.zip"
    },
    "celeste.zip": {
      "file": "celeste/celeste.port.json",
      "items": ["Celeste.sh", "celeste/"],
      "name": "celeste.zip"
    },
    "commander.genius.zip": {
      "file": "cgenius/commander.genius.port.json",
      "items": ["cgenius/", "Commander Genius.sh"],
      "name": "commander.genius.zip"
    },
    "corsixth.zip": {
      "file": "CorsixTH/corsixth.port.json",
      "items": ["CorsixTH/", "CorsixTH.sh"],
      "name": "corsixth.zip"
    },
    "cosmo-engine.zip": {
      "file": "cosmo-engine/cosmo-engine.port.json",
      "items": ["cosmo-engine/", "Cosmos Cosmic Adventure.sh"],
      "name": "cosmo-engine.zip"
    },
    "cromagrally.zip": {
      "file": "cromagrally/cromagrally.port.json",
      "items": ["CroMagRally.sh", "cromagrally/"],
      "name": "cromagrally.zip"
    },
    "davegnukem.zip": {
      "file": "davegnukem/davegnukem.port.json",
      "items": ["Dave Gnukem.sh", "davegnukem/"],
      "name": "davegnukem.zip"
    },
    "derclou.zip": {
      "file": "derclou/derclou.port.json",
      "items": ["Der Clou.sh", "derclou/"],
      "name": "derclou.zip"
    },
    "devilutionx.zip": {
      "file": "devilution/devilutionx.port.json",
      "items": ["devilution/", "Devilutionx.sh"],
      "name": "devilutionx.zip"
    },
    "dinothawr.zip": {
      "file": "dinothawr/dinothawr.port.json",
      "items": ["Dinothawr.sh", "dinothawr/"],
      "name": "dinothawr.zip"
    },
    "diverdown.zip": {
      "file": "diverdown/diverdown.port.json",
      "items": ["DiverDown.sh", "diverdown/"],
      "name": "diverdown.zip"
    },
    "doom3.zip": {
      "file": "doom3/doom3.port.json",
      "items": ["Doom 3.sh", "doom3/"],
      "name": "doom3.zip"
    },
    "duke.nukem.3d.zip": {
      "file": "rednukem-dn3d-atomic/duke.nukem.3d.port.json",
      "items": ["Duke Nukem 3D.sh", "rednukem-dn3d-atomic/"],
      "name": "duke.nukem.3d.zip"
    },
    "dungeonrush.zip": {
      "file": "dungeonrush/dungeonrush.port.json",
      "items": ["dungeonrush/", "DungeonRush.sh"],
      "name": "dungeonrush.zip"
    },
    "eity.zip": {
      "file": "eity/eity.port.json",
      "items": ["Eity.sh", "eity/"],
      "name": "eity.zip"
    },
    "enigma.zip": {
      "file": "enigma/enigma.port.json",
      "items": ["enigma/", "Enigma.sh"],
      "name": "enigma.zip"
    },
    "exhumed.zip": {
      "file": "Exhumed/exhumed.port.json",
      "items": ["Exhumed.sh", "Exhumed/"],
      "name": "exhumed.zip"
    },
    "exult.zip": {
      "file": "exult/exult.port.json",
      "items": ["exult/", "Exult-keyring.sh", "Exult-nokeyring.sh"],
      "name": "exult.zip"
    },
    "fade_to_black.zip": {
      "file": "f2bgl/fade_to_black.port.json",
      "items": ["f2bgl/", "F2bgl.sh"],
      "name": "fade_to_black.zip"
    },
    "falling_time.zip": {
      "file": "falling_time/falling_time.port.json",
      "items": ["Falling Time.sh", "falling_time/"],
      "name": "falling_time.zip"
    },
    "fallout1.zip": {
      "file": "fallout1/fallout1.port.json",
      "items": ["Fallout 1.sh", "fallout1/"],
      "name": "fallout1.zip"
    },
    "fallout2.zip": {
      "file": "fallout2/fallout2.port.json",
      "items": ["Fallout 2.sh", "fallout2/"],
      "name": "fallout2.zip"
    },
    "fheroes2.zip": {
      "file": "fheroes2/fheroes2.port.json",
      "items": ["fheroes2/", "Fheroes2.sh"],
      "name": "fheroes2.zip"
    },
    "flare.zip": {
      "file": "flare/flare.port.json",
      "items": ["Flare Engine.sh", "flare/"],
      "name": "flare.zip"
    },
    "freedom.planet.zip": {
      "file": "freedomplanet/freedom.planet.port.json",
      "items": ["Freedom Planet.sh", "freedomplanet/"],
      "name": "freedom.planet.zip"
    },
    "freedroid.zip": {
      "file": "freedroid/freedroid.port.json",
      "items": ["Freedroid.sh", "freedroid/"],
      "name": "freedroid.zip"
    },
    "freegemas.zip": {
      "file": "freegemas/freegemas.port.json",
      "items": ["freegemas/", "Freegemas.sh"],
      "name": "freegemas.zip"
    },
    "freeserf.zip": {
      "file": "freeserf/freeserf.port.json",
      "items": ["FreeSerf.sh", "freeserf/"],
      "name": "freeserf.zip"
    },
    "gemrb.zip": {
      "file": "gemrb/gemrb.port.json",
      "items": ["GemRB.sh", "gemrb/"],
      "name": "gemrb.zip"
    },
    "gigalomania.zip": {
      "file": "gigalomania/gigalomania.port.json",
      "items": ["Gigalomania.sh", "gigalomania/"],
      "name": "gigalomania.zip"
    },
    "half-life.2.zip": {
      "file": "halflife2/half-life.2.port.json",
      "items": ["Half-Life 2.sh", "halflife2/"],
      "name": "half-life.2.zip"
    },
    "half-life.zip": {
      "file": "Half-Life/half-life.port.json",
      "items": ["Half-Life.sh", "Half-Life/"],
      "items_opt": ["Half-Life Blue Shift.sh", "Half-Life Opposing Forces.sh"],
      "name": "half-life.zip"
    },
    "heart.of.darkness.zip": {
      "file": "hode/heart.of.darkness.port.json",
      "items": ["Heart of Darkness.sh", "hode/"],
      "name": "heart.of.darkness.zip"
    },
    "hex-a-hop.zip": {
      "file": "hex-a-hop/hex-a-hop.port.json",
      "items": ["Hex-A-Hop.sh", "hex-a-hop/"],
      "name": "hex-a-hop.zip"
    },
    "hexen2.zip": {
      "file": "hexen2/hexen2.port.json",
      "items": ["Hexen 2 - Portal of Praevus.sh", "Hexen 2.sh", "hexen2/"],
      "name": "hexen2.zip"
    },
    "hijinx.zip": {
      "file": "hijinx/hijinx.port.json",
      "items": ["Hijinx.sh", "hijinx/"],
      "name": "hijinx.zip"
    },
    "hocoslamfy.zip": {
      "file": "hocoslamfy/hocoslamfy.port.json",
      "items": ["Hocoslamfy.sh", "hocoslamfy/"],
      "name": "hocoslamfy.zip"
    },
    "hurrican.zip": {
      "file": "hurrican/hurrican.port.json",
      "items": ["hurrican/", "Hurrican.sh"],
      "name": "hurrican.zip"
    },
    "hydra.castle.labyrinth.zip": {
      "file": "hcl/hydra.castle.labyrinth.port.json",
      "items": ["hcl/", "Hydra Castle Labyrinth.sh"],
      "name": "hydra.castle.labyrinth.zip"
    },
    "iconoclasts.zip": {
      "file": "iconoclasts/iconoclasts.port.json",
      "items": ["iconoclasts/", "Iconoclasts.sh"],
      "name": "iconoclasts.zip"
    },
    "iichantra_pear.zip": {
      "file": "iichantra_pear/iichantra_pear.port.json",
      "items": ["IIChantra P.E.A.R.sh", "iichantra_pear/"],
      "name": "iichantra_pear.zip"
    },
    "invaders.zip": {
      "file": "Invaders/invaders.port.json",
      "items": ["Invaders.sh", "Invaders/"],
      "name": "invaders.zip"
    },
    "iortcw.zip": {
      "file": "iortcw/iortcw.port.json",
      "items": ["iortcw/", "Return to Castle Wolfenstein.sh"],
      "name": "iortcw.zip"
    },
    "jediacademy.zip": {
      "file": "JediAcademy/jediacademy.port.json",
      "items": ["JediAcademy/", "Star Wars Jedi Knight - Jedi Academy.sh"],
      "name": "jediacademy.zip"
    },
    "jedioutcast.zip": {
      "file": "JediOutcast/jedioutcast.port.json",
      "items": ["JediOutcast/", "Star Wars Jedi Knight II - Jedi Outcast.sh"],
      "name": "jedioutcast.zip"
    },
    "maldita.castilla.zip": {
      "file": "MalditaCastilla/maldita.castilla.port.json",
      "items": ["Maldita Castilla.sh", "MalditaCastilla/"],
      "name": "maldita.castilla.zip"
    },
    "meritous.zip": {
      "file": "meritous/meritous.port.json",
      "items": ["Meritous.sh", "meritous/"],
      "name": "meritous.zip"
    },
    "mightymike.zip": {
      "file": "mightymike/mightymike.port.json",
      "items": ["MightyMike.sh", "mightymike/"],
      "name": "mightymike.zip"
    },
    "mirrormagic.zip": {
      "file": "mirrormagic/mirrormagic.port.json",
      "items": ["Mirror Magic.sh", "mirrormagic/"],
      "name": "mirrormagic.zip"
    },
    "moonlight.zip": {
      "file": "moonlight/moonlight.port.json",
      "items": ["moonlight/", "Moonlight.sh"],
      "name": "moonlight.zip"
    },
    "mr.boom.zip": {
      "file": "mrboom/mr.port.json",
      "items": ["Mr. Boom.sh", "mrboom/"],
      "name": "mr.boom.zip"
    },
    "multris.zip": {
      "file": "multris/multris.port.json",
      "items": ["multris/", "Multris.sh"],
      "name": "multris.zip"
    },
    "nam.zip": {
      "file": "rednukem-NAM/nam.port.json",
      "items": ["NAM.sh", "rednukem-NAM/"],
      "name": "nam.zip"
    },
    "nanosaur.zip": {
      "file": "nanosaur/nanosaur.port.json",
      "items": ["Nanosaur.sh", "nanosaur/"],
      "name": "nanosaur.zip"
    },
    "neverball.zip": {
      "file": "neverball/neverball.port.json",
      "items": ["neverball/", "Neverball.sh", "Neverputt.sh"],
      "name": "neverball.zip"
    },
    "nkaruga.zip": {
      "file": "nkaruga/nkaruga.port.json",
      "items": ["nkaruga/", "nKaruga.sh"],
      "name": "nkaruga.zip"
    },
    "nonny.zip": {
      "file": "nonny/nonny.port.json",
      "items": ["nonny/", "Nonny.sh"],
      "name": "nonny.zip"
    },
    "oddworld.zip": {
      "file": "relive/oddworld.port.json",
      "items": ["Oddworld Abes Oddysee.sh", "Oddworld Abes Exoddus.sh", "relive/"],
      "name": "oddworld.zip"
    },
    "openblok.zip": {
      "file": "openblok/openblok.port.json",
      "items": ["openblok/", "OpenBlok.sh"],
      "name": "openblok.zip"
    },
    "openclaw.zip": {
      "file": "openclaw/openclaw.port.json",
      "items": ["Openclaw.sh", "openclaw/"],
      "name": "openclaw.zip"
    },
    "openfodder.zip": {
      "file": "openfodder/openfodder.port.json",
      "items": ["OpenFodder.sh", "openfodder/"],
      "name": "openfodder.zip"
    },
    "openjazz.zip": {
      "file": "openjazz/openjazz.port.json",
      "items": ["openjazz/", "OpenJazz.sh"],
      "name": "openjazz.zip"
    },
    "openomf.zip": {
      "file": "openomf/openomf.port.json",
      "items": ["openomf/", "Openomf.sh"],
      "name": "openomf.zip"
    },
    "openrct2.zip": {
      "file": "openrct2/openrct2.port.json",
      "items": ["OpenRCT2.sh", "openrct2/"],
      "name": "openrct2.zip"
    },
    "openttd.zip": {
      "file": "openttd/openttd.port.json",
      "items": ["openttd/", "Openttd.sh"],
      "name": "openttd.zip"
    },
    "opentyrian.zip": {
      "file": "opentyrian/opentyrian.port.json",
      "items": ["OpenTyrian.sh", "opentyrian/"],
      "name": "opentyrian.zip"
    },
    "openxcom.zip": {
      "file": "openxcom/openxcom.port.json",
      "items": ["openxcom/", "OpenXcomEX.sh"],
      "name": "openxcom.zip"
    },
    "ottomatic.zip": {
      "file": "ottomatic/ottomatic.port.json",
      "items": ["OttoMatic.sh", "ottomatic/"],
      "name": "ottomatic.zip"
    },
    "owlboy.zip": {
      "file": "owlboy/owlboy.port.json",
      "items": ["owlboy/", "Owlboy.sh"],
      "name": "owlboy.zip"
    },
    "pekka-kana-2.zip": {
      "file": "pekka-kana-2/pekka-kana-2.port.json",
      "items": ["Pekka Kana 2.sh", "pekka-kana-2/"],
      "name": "pekka-kana-2.zip"
    },
    "powder.zip": {
      "file": "powder/powder.port.json",
      "items": ["Powder.sh", "powder/"],
      "name": "powder.zip"
    },
    "prehistorik.2.zip": {
      "file": "prehistorik2/prehistorik.2.port.json",
      "items": ["Prehistorik 2.sh", "prehistorik2/"],
      "name": "prehistorik.2.zip"
    },
    "profadeluxe.zip": {
      "file": "profadeluxe/profadeluxe.port.json",
      "items": ["Abu Simbel Profanation Deluxe.sh", "profadeluxe/"],
      "name": "profadeluxe.zip"
    },
    "quake.2.zip": {
      "file": "quake2/quake.2.port.json",
      "items": ["Quake 2.sh", "quake2/"],
      "name": "quake.2.zip"
    },
    "quake.zip": {
      "file": "quake/quake.port.json",
      "items": ["quake/", "Quake.sh"],
      "name": "quake.zip"
    },
    "quake3.zip": {
      "file": "quake3/quake3.port.json",
      "items": ["Quake 3.sh", "quake3/"],
      "name": "quake3.zip"
    },
    "rawgl.zip": {
      "file": "rawgl/rawgl.port.json",
      "items": ["RAWGL.sh", "rawgl/"],
      "name": "rawgl.zip"
    },
    "redneck.rampage.rides.again.zip": {
      "file": "rednukem-redneck2/redneck.rampage.rides.again.port.json",
      "items": ["Redneck Rampage Rides Again.sh", "rednukem-redneck2/"],
      "name": "redneck.rampage.rides.again.zip"
    },
    "redneck.rampage.zip": {
      "file": "rednukem-redneck1/redneck.rampage.port.json",
      "items": ["Redneck Rampage.sh", "rednukem-redneck1/"],
      "name": "redneck.rampage.zip"
    },
    "reminiscence.zip": {
      "file": "reminiscence/reminiscence.port.json",
      "items": ["reminiscence/", "REminiscence.sh"],
      "name": "reminiscence.zip"
    },
    "ri_li.zip": {
      "file": "ri_li/ri_li.port.json",
      "items": ["Ri-Li.sh", "ri_li/"],
      "name": "ri_li.zip"
    },
    "rick.dangerous.zip": {
      "file": "xrick/rick.dangerous.port.json",
      "items": ["Rick Dangerous.sh", "xrick/"],
      "name": "rick.dangerous.zip"
    },
    "rigelengine.zip": {
      "file": "RigelEngine/rigelengine.port.json",
      "items": ["RigelEngine/", "RigelEngine.sh"],
      "name": "rigelengine.zip"
    },
    "rlvm.zip": {
      "file": "rlvm/rlvm.port.json",
      "items": ["Rlvm.sh", "rlvm/"],
      "name": "rlvm.zip"
    },
    "rocksndiamonds.zip": {
      "file": "rocksndiamonds/rocksndiamonds.port.json",
      "items": ["Rocks n Diamonds.sh", "rocksndiamonds/"],
      "name": "rocksndiamonds.zip"
    },
    "rott.zip": {
      "file": "rott/rott.port.json",
      "items": ["rott/", "ROTT.sh"],
      "name": "rott.zip"
    },
    "rvgl.zip": {
      "file": "rvgl/rvgl.port.json",
      "items": ["rvgl/", "RVGL.sh"],
      "name": "rvgl.zip"
    },
    "sdlpop.zip": {
      "file": "sdlpop/sdlpop.port.json",
      "items": ["sdlpop/", "SDLPoP.sh"],
      "name": "sdlpop.zip"
    },
    "shadow.warrior.zip": {
      "file": "shadow-warrior/shadow.warrior.port.json",
      "items": ["Shadow Warrior.sh", "shadow-warrior/"],
      "name": "shadow.warrior.zip"
    },
    "shipwreck.zip": {
      "file": "shipwreck/shipwreck.port.json",
      "items": ["shipwreck/", "Shipwreck.sh"],
      "name": "shipwreck.zip"
    },
    "shovel.knight.zip": {
      "file": "shovelknight/shovel.knight.port.json",
      "items": ["Shovel Knight.sh", "shovelknight/"],
      "name": "shovel.knight.zip"
    },
    "simplesokoban.zip": {
      "file": "simplesok/simplesokoban.port.json",
      "items": ["Simple Sokoban.sh", "simplesok/"],
      "name": "simplesokoban.zip"
    },
    "skijump3.zip": {
      "file": "skijump3/skijump3.port.json",
      "items": ["skijump3/", "Skijump3.sh"],
      "name": "skijump3.zip"
    },
    "sm64.zip": {
      "file": "sm64/sm64.port.json",
      "items": ["sm64.sh", "sm64/"],
      "name": "sm64.zip"
    },
    "sonic.1.zip": {
      "file": "sonic1/sonic.1.port.json",
      "items": ["Sonic 1.sh", "sonic1/"],
      "name": "sonic.1.zip"
    },
    "sonic.2.zip": {
      "file": "sonic2/sonic.2.port.json",
      "items": ["Sonic 2.sh", "sonic2/"],
      "name": "sonic.2.zip"
    },
    "sonic.cd.zip": {
      "file": "soniccd/sonic.cd.port.json",
      "items": ["Sonic CD.sh", "soniccd/"],
      "name": "sonic.cd.zip"
    },
    "sonic.mania.zip": {
      "file": "sonicmania/sonic.mania.port.json",
      "items": ["Sonic Mania.sh", "sonicmania/"],
      "name": "sonic.mania.zip"
    },
    "sorr.zip": {
      "file": "sorr/sorr.port.json",
      "items": ["sorr/", "SorR.sh"],
      "name": "sorr.zip"
    },
    "space.cadet.pinball.zip": {
      "file": "spacecadetpinball/space.cadet.pinball.port.json",
      "items": ["Space Cadet Pinball.sh", "spacecadetpinball/"],
      "name": "space.cadet.pinball.zip"
    },
    "spelunky.zip": {
      "file": "spelunky/spelunky.port.json",
      "items": ["spelunky/", "Spelunky.sh"],
      "name": "spelunky.zip"
    },
    "srb2.zip": {
      "file": "SRB2/srb2.port.json",
      "items": ["SRB2/", "SRB2.sh"],
      "name": "srb2.zip"
    },
    "srb2kart.zip": {
      "file": "srb2kart/srb2kart.port.json",
      "items": ["Sonic Robo Blast 2 Kart.sh", "srb2kart/"],
      "name": "srb2kart.zip"
    },
    "starcatcher.zip": {
      "file": "starcatcher/starcatcher.port.json",
      "items": ["Starcatcher.sh", "starcatcher/"],
      "name": "starcatcher.zip"
    },
    "stardewvalley.zip": {
      "file": "stardewvalley/stardewvalley.port.json",
      "items": ["stardewvalley/", "StardewValley.sh"],
      "name": "stardewvalley.zip"
    },
    "steelassault.zip": {
      "file": "steelassault/steelassault.port.json",
      "items": ["steelassault/", "SteelAssault.sh"],
      "name": "steelassault.zip"
    },
    "super.mario.war.zip": {
      "file": "smw/super.mario.war.port.json",
      "items": ["smw/", "Super Mario War.sh"],
      "name": "super.mario.war.zip"
    },
    "supertux.zip": {
      "file": "supertux/supertux.port.json",
      "items": ["supertux/", "SuperTux.sh"],
      "name": "supertux.zip"
    },
    "tamatool.zip": {
      "file": "tamatool/tamatool.port.json",
      "items": ["tamatool/", "Tamatool.sh"],
      "name": "tamatool.zip"
    },
    "thermomorph.zip": {
      "file": "thermomorph/thermomorph.port.json",
      "items": ["Thermomorph.sh", "thermomorph/"],
      "name": "thermomorph.zip"
    },
    "tileworld.zip": {
      "file": "tileworld/tileworld.port.json",
      "items": [
        "Tile World (Chip's Challenge).sh",
        "Tile World (Natural Theme Mod).sh",
        "tileworld/"
      ],
      "name": "tileworld.zip"
    },
    "timespinner.zip": {
      "file": "timespinner/timespinner.port.json",
      "items": ["timespinner/", "Timespinner.sh"],
      "name": "timespinner.zip"
    },
    "tiny-crate.zip": {
      "file": "tiny-crate/tiny-crate.port.json",
      "items": ["Tiny Crate.sh", "tiny-crate/"],
      "name": "tiny-crate.zip"
    },
    "titan_tactics.zip": {
      "file": "titan_tactics/titan_tactics.port.json",
      "items": ["Titan Tactics.sh", "titan_tactics/"],
      "name": "titan_tactics.zip"
    },
    "tmntsr.zip": {
      "file": "tmntsr/tmntsr.port.json",
      "items": ["TMNTShreddersRevenge.sh", "tmntsr/"],
      "name": "tmntsr.zip"
    },
    "tomb.raider.1.zip": {
      "file": "tombraider1/tomb.raider.1.port.json",
      "items": ["Tomb Raider 1.sh", "tombraider1/"],
      "name": "tomb.raider.1.zip"
    },
    "ultimatetapankaikki.zip": {
      "file": "ultimatetapankaikki/ultimatetapankaikki.port.json",
      "items": ["Ultimatetapankaikki.sh", "ultimatetapankaikki/"],
      "name": "ultimatetapankaikki.zip"
    },
    "undertale.zip": {
      "file": "undertale/undertale.port.json",
      "items": ["undertale/", "Undertale.sh"],
      "name": "undertale.zip"
    },
    "upo.zip": {
      "file": "upo/upo.port.json",
      "items": ["Upo.sh", "upo/"],
      "name": "upo.zip"
    },
    "uqm.zip": {
      "file": "UQM/uqm.port.json",
      "items": ["UQM/", "UQM.sh"],
      "name": "uqm.zip"
    },
    "vanillara.zip": {
      "file": "vanillara/vanillara.port.json",
      "items": ["VanillaRA.sh", "vanillara/"],
      "name": "vanillara.zip"
    },
    "vanillatd.zip": {
      "file": "vanillatd/vanillatd.port.json",
      "items": ["VanillaTD.sh", "vanillatd/"],
      "name": "vanillatd.zip"
    },
    "vcmi.zip": {
      "file": "vcmi/vcmi.port.json",
      "items": ["VCMI.sh", "vcmi/"],
      "name": "vcmi.zip"
    },
    "vvvvvv.zip": {
      "file": "VVVVVV/vvvvvv.port.json",
      "items": ["VVVVVV/", "VVVVVV.sh"],
      "name": "vvvvvv.zip"
    },
    "wetspot2.zip": {
      "file": "wetspot2/wetspot2.port.json",
      "items": ["Wetspot2.sh", "wetspot2/"],
      "name": "wetspot2.zip"
    },
    "wordlesdl.zip": {
      "file": "wordlesdl/wordlesdl.port.json",
      "items": ["Wordle SDL.sh", "wordlesdl/"],
      "name": "wordlesdl.zip"
    },
    "world.war.ii.gi.zip": {
      "file": "rednukem-WWII/world.war.ii.gi.port.json",
      "items": ["rednukem-WWII/", "World War II GI.sh"],
      "name": "world.war.ii.gi.zip"
    },
    "worship_vector.zip": {
      "file": "worship/worship_vector.port.json",
      "items": ["Worship Vector.sh", "worship/"],
      "name": "worship_vector.zip"
    },
    "zgloom.zip": {
      "file": "zgloom/zgloom.port.json",
      "items": [
        "Gloom - Zombie Massacre.sh",
        "Gloom 3.sh",
        "Gloom Deluxe.sh",
        "Gloom.sh",
        "zgloom/"
      ],
      "name": "zgloom.zip"
    }
  }
}
