# -- Autogenerated by tools/ports_analyse.py --
# -- 2023-04-27 18:52:04 --

ports_info = {
  "items": {
    "2048.sh": "2048.zip",
    "2048/": "2048.zip",
    "Abes Adventure.sh": "abes_adventure.zip",
    "abes_adventure/": "abes_adventure.zip",
    "Abu Simbel Profanation Deluxe.sh": "profadeluxe.zip",
    "Abuse.sh": "abuse.zip",
    "Abuse/": "abuse.zip",
    "alephone/": [
      "alephone-marathon.zip",
      "alephone-marathon2.zip",
      "alephone-marathoninfinity.zip"
    ],
    "Alien vs Predator.sh": "avp.zip",
    "AM2R.sh": "am2r.zip",
    "am2r/": "am2r.zip",
    "Anarch.sh": "anarch.zip",
    "anarch/": "anarch.zip",
    "Augustus.sh": "augustus.zip",
    "augustus/": "augustus.zip",
    "avp/": "avp.zip",
    "Axiom Verge.sh": "axiom.verge.zip",
    "axiom-verge/": "axiom.verge.zip",
    "Bermuda Syndrome.sh": "bermuda_syndrome.zip",
    "bermuda/": "bermuda_syndrome.zip",
    "BillyFrontier.sh": "billyfrontier.zip",
    "billyfrontier/": "billyfrontier.zip",
    "Blake Stone - Aliens of Gold.sh": "bstone-aog.zip",
    "Blake Stone - Planet Strike.sh": "bstone-ps.zip",
    "Blobby Volley 2.sh": "blobby.volley2.zip",
    "blobbyvolley2/": "blobby.volley2.zip",
    "Blobwars.sh": "blobwars.zip",
    "blobwars/": "blobwars.zip",
    "Block Attack.sh": "block.attack.zip",
    "blockattack/": "block.attack.zip",
    "Blockout 2.sh": "blockout2.zip",
    "blockout2/": "blockout2.zip",
    "Blood.sh": "blood.zip",
    "Blood/": "blood.zip",
    "Blues Brothers Jukebox Adventure.sh": "bbja.zip",
    "Blues Brothers.sh": "blues.brothers.zip",
    "bluesbrothers/": "blues.brothers.zip",
    "bstone-aog/": "bstone-aog.zip",
    "bstone-ps/": "bstone-ps.zip",
    "Bugdom.sh": "bugdom.zip",
    "bugdom/": "bugdom.zip",
    "C-Dogs.sh": "c-dogs.zip",
    "Cannonball.sh": "cannonball.zip",
    "cannonball/": "cannonball.zip",
    "Cave Story-evo.sh": "cave.story-evo.zip",
    "Cave Story.sh": "cave.story.zip",
    "cavestory/": "cave.story.zip",
    "cdogs/": "c-dogs.zip",
    "Celeste.sh": "celeste.zip",
    "celeste/": "celeste.zip",
    "cgenius/": "commander.genius.zip",
    "Commander Genius.sh": "commander.genius.zip",
    "CorsixTH.sh": "corsixth.zip",
    "CorsixTH/": "corsixth.zip",
    "cosmo-engine/": "cosmo-engine.zip",
    "Cosmos Cosmic Adventure.sh": "cosmo-engine.zip",
    "CroMagRally.sh": "cromagrally.zip",
    "cromagrally/": "cromagrally.zip",
    "Dave Gnukem.sh": "davegnukem.zip",
    "davegnukem/": "davegnukem.zip",
    "Der Clou.sh": "derclou.zip",
    "derclou/": "derclou.zip",
    "devilution/": "devilutionx.zip",
    "Devilutionx.sh": "devilutionx.zip",
    "Dinothawr.sh": "dinothawr.zip",
    "dinothawr/": "dinothawr.zip",
    "DiverDown.sh": "diverdown.zip",
    "diverdown/": "diverdown.zip",
    "Doom 3.sh": "doom3.zip",
    "doom3/": "doom3.zip",
    "Duke Nukem 3D.sh": "duke.nukem.3d.zip",
    "DungeonRush.sh": "dungeonrush.zip",
    "dungeonrush/": "dungeonrush.zip",
    "Enigma.sh": "enigma.zip",
    "enigma/": "enigma.zip",
    "Exhumed.sh": "exhumed.zip",
    "Exhumed/": "exhumed.zip",
    "Exult-keyring.sh": "exult.zip",
    "Exult-nokeyring.sh": "exult.zip",
    "exult/": "exult.zip",
    "F2bgl.sh": "fade_to_black.zip",
    "f2bgl/": "fade_to_black.zip",
    "Falling Time.sh": "falling_time.zip",
    "falling_time/": "falling_time.zip",
    "Fallout 1.sh": "fallout1.zip",
    "Fallout 2.sh": "fallout2.zip",
    "fallout1/": "fallout1.zip",
    "fallout2/": "fallout2.zip",
    "Fheroes2.sh": "fheroes2.zip",
    "fheroes2/": "fheroes2.zip",
    "Flare Engine.sh": "flare.zip",
    "flare/": "flare.zip",
    "Freedom Planet.sh": "freedom.planet.zip",
    "freedomplanet/": "freedom.planet.zip",
    "Freedroid.sh": "freedroid.zip",
    "freedroid/": "freedroid.zip",
    "Freegemas.sh": "freegemas.zip",
    "freegemas/": "freegemas.zip",
    "FreeSerf.sh": "freeserf.zip",
    "freeserf/": "freeserf.zip",
    "GemRB.sh": "gemrb.zip",
    "gemrb/": "gemrb.zip",
    "Gigalomania.sh": "gigalomania.zip",
    "gigalomania/": "gigalomania.zip",
    "Half-Life 2.sh": "half-life.2.zip",
    "Half-Life Blue Shift.sh": "half-life.zip",
    "Half-Life Opposing Forces.sh": "half-life.zip",
    "Half-Life.sh": "half-life.zip",
    "Half-Life/": "half-life.zip",
    "halflife2/": "half-life.2.zip",
    "hcl/": "hydra.castle.labyrinth.zip",
    "Heart of Darkness.sh": "heart.of.darkness.zip",
    "Hex-A-Hop.sh": "hex-a-hop.zip",
    "hex-a-hop/": "hex-a-hop.zip",
    "Hexen 2 - Portal of Praevus.sh": "hexen2.zip",
    "Hexen 2.sh": "hexen2.zip",
    "hexen2/": "hexen2.zip",
    "Hijinx.sh": "hijinx.zip",
    "hijinx/": "hijinx.zip",
    "Hocoslamfy.sh": "hocoslamfy.zip",
    "hocoslamfy/": "hocoslamfy.zip",
    "hode/": "heart.of.darkness.zip",
    "Hurrican.sh": "hurrican.zip",
    "hurrican/": "hurrican.zip",
    "Hydra Castle Labyrinth.sh": "hydra.castle.labyrinth.zip",
    "Iconoclasts.sh": "iconoclasts.zip",
    "iconoclasts/": "iconoclasts.zip",
    "IIChantra P.E.A.R.sh": "iichantra_pear.zip",
    "iichantra_pear/": "iichantra_pear.zip",
    "Invaders.sh": "invaders.zip",
    "Invaders/": "invaders.zip",
    "iortcw/": "iortcw.zip",
    "JediAcademy/": "jediacademy.zip",
    "JediOutcast/": "jedioutcast.zip",
    "jukeboxadventure/": "bbja.zip",
    "Maldita Castilla.sh": "maldita.castilla.zip",
    "MalditaCastilla/": "maldita.castilla.zip",
    "Marathon 2.sh": "alephone-marathon2.zip",
    "Marathon Infinity.sh": "alephone-marathoninfinity.zip",
    "Marathon.sh": "alephone-marathon.zip",
    "Meritous.sh": "meritous.zip",
    "meritous/": "meritous.zip",
    "MightyMike.sh": "mightymike.zip",
    "mightymike/": "mightymike.zip",
    "Mirror Magic.sh": "mirrormagic.zip",
    "mirrormagic/": "mirrormagic.zip",
    "Moonlight.sh": "moonlight.zip",
    "moonlight/": "moonlight.zip",
    "Mr. Boom.sh": "mr.boom.zip",
    "mrboom/": "mr.boom.zip",
    "Multris.sh": "multris.zip",
    "multris/": "multris.zip",
    "NAM.sh": "nam.zip",
    "Nanosaur.sh": "nanosaur.zip",
    "nanosaur/": "nanosaur.zip",
    "Neverball.sh": "neverball.zip",
    "neverball/": "neverball.zip",
    "Neverputt.sh": "neverball.zip",
    "nKaruga.sh": "nkaruga.zip",
    "nkaruga/": "nkaruga.zip",
    "nxengine-evo/": "cave.story-evo.zip",
    "Oddworld Abes Exoddus.sh": "oddworld.zip",
    "Oddworld Abes Oddysee.sh": "oddworld.zip",
    "OpenBlok.sh": "openblok.zip",
    "openblok/": "openblok.zip",
    "Openclaw.sh": "openclaw.zip",
    "openclaw/": "openclaw.zip",
    "OpenFodder.sh": "openfodder.zip",
    "openfodder/": "openfodder.zip",
    "OpenJazz.sh": "openjazz.zip",
    "openjazz/": "openjazz.zip",
    "Openomf.sh": "openomf.zip",
    "openomf/": "openomf.zip",
    "OpenRCT2.sh": "openrct2.zip",
    "openrct2/": "openrct2.zip",
    "Openttd.sh": "openttd.zip",
    "openttd/": "openttd.zip",
    "OpenTyrian.sh": "opentyrian.zip",
    "opentyrian/": "opentyrian.zip",
    "openxcom/": "openxcom.zip",
    "OpenXcomEX.sh": "openxcom.zip",
    "OttoMatic.sh": "ottomatic.zip",
    "ottomatic/": "ottomatic.zip",
    "Owlboy.sh": "owlboy.zip",
    "owlboy/": "owlboy.zip",
    "Pekka Kana 2.sh": "pekka-kana-2.zip",
    "pekka-kana-2/": "pekka-kana-2.zip",
    "Powder.sh": "powder.zip",
    "powder/": "powder.zip",
    "Prehistorik 2.sh": "prehistorik.2.zip",
    "prehistorik2/": "prehistorik.2.zip",
    "profadeluxe/": "profadeluxe.zip",
    "Quake 2.sh": "quake.2.zip",
    "Quake 3.sh": "quake3.zip",
    "Quake.sh": "quake.zip",
    "quake/": "quake.zip",
    "quake2/": "quake.2.zip",
    "quake3/": "quake3.zip",
    "RAWGL.sh": "rawgl.zip",
    "rawgl/": "rawgl.zip",
    "Redneck Rampage Rides Again.sh": "redneck.rampage.rides.again.zip",
    "Redneck Rampage.sh": "redneck.rampage.zip",
    "rednukem-dn3d-atomic/": "duke.nukem.3d.zip",
    "rednukem-NAM/": "nam.zip",
    "rednukem-redneck1/": "redneck.rampage.zip",
    "rednukem-redneck2/": "redneck.rampage.rides.again.zip",
    "rednukem-WWII/": "world.war.ii.gi.zip",
    "relive/": "oddworld.zip",
    "REminiscence.sh": "reminiscence.zip",
    "reminiscence/": "reminiscence.zip",
    "Return to Castle Wolfenstein.sh": "iortcw.zip",
    "Ri-Li.sh": "ri_li.zip",
    "ri_li/": "ri_li.zip",
    "Rick Dangerous.sh": "rick.dangerous.zip",
    "RigelEngine.sh": "rigelengine.zip",
    "RigelEngine/": "rigelengine.zip",
    "Rlvm.sh": "rlvm.zip",
    "rlvm/": "rlvm.zip",
    "Rocks n Diamonds.sh": "rocksndiamonds.zip",
    "rocksndiamonds/": "rocksndiamonds.zip",
    "ROTT.sh": "rott.zip",
    "rott/": "rott.zip",
    "RVGL.sh": "rvgl.zip",
    "rvgl/": "rvgl.zip",
    "SDLPoP.sh": "sdlpop.zip",
    "sdlpop/": "sdlpop.zip",
    "Shadow Warrior.sh": "shadow.warrior.zip",
    "shadow-warrior/": "shadow.warrior.zip",
    "Shipwreck.sh": "shipwreck.zip",
    "shipwreck/": "shipwreck.zip",
    "Shovel Knight.sh": "shovel.knight.zip",
    "shovelknight/": "shovel.knight.zip",
    "Simple Sokoban.sh": "simplesokoban.zip",
    "simplesok/": "simplesokoban.zip",
    "Skijump3.sh": "skijump3.zip",
    "skijump3/": "skijump3.zip",
    "sm64.sh": "sm64.zip",
    "sm64/": "sm64.zip",
    "smw/": "super.mario.war.zip",
    "Sonic 1.sh": "sonic.1.zip",
    "Sonic 2.sh": "sonic.2.zip",
    "Sonic CD.sh": "sonic.cd.zip",
    "Sonic Mania.sh": "sonic.mania.zip",
    "Sonic Robo Blast 2 Kart.sh": "srb2kart.zip",
    "sonic1/": "sonic.1.zip",
    "sonic2/": "sonic.2.zip",
    "soniccd/": "sonic.cd.zip",
    "sonicmania/": "sonic.mania.zip",
    "SorR.sh": "sorr.zip",
    "sorr/": "sorr.zip",
    "Space Cadet Pinball.sh": "space.cadet.pinball.zip",
    "spacecadetpinball/": "space.cadet.pinball.zip",
    "Spelunky.sh": "spelunky.zip",
    "spelunky/": "spelunky.zip",
    "SRB2.sh": "srb2.zip",
    "SRB2/": "srb2.zip",
    "srb2kart/": "srb2kart.zip",
    "Star Wars Jedi Knight - Jedi Academy.sh": "jediacademy.zip",
    "Star Wars Jedi Knight II - Jedi Outcast.sh": "jedioutcast.zip",
    "Starcatcher.sh": "starcatcher.zip",
    "starcatcher/": "starcatcher.zip",
    "StardewValley.sh": "stardewvalley.zip",
    "stardewvalley/": "stardewvalley.zip",
    "SteelAssault.sh": "steelassault.zip",
    "steelassault/": "steelassault.zip",
    "Super Mario War.sh": "super.mario.war.zip",
    "SuperTux.sh": "supertux.zip",
    "supertux/": "supertux.zip",
    "Tamatool.sh": "tamatool.zip",
    "tamatool/": "tamatool.zip",
    "Tile World (Chip's Challenge).sh": "tileworld.zip",
    "Tile World (Natural Theme Mod).sh": "tileworld.zip",
    "tileworld/": "tileworld.zip",
    "Timespinner.sh": "timespinner.zip",
    "timespinner/": "timespinner.zip",
    "Tiny Crate.sh": "tiny-crate.zip",
    "tiny-crate/": "tiny-crate.zip",
    "Titan Tactics.sh": "titan_tactics.zip",
    "titan_tactics/": "titan_tactics.zip",
    "TMNTShreddersRevenge.sh": "tmntsr.zip",
    "tmntsr/": "tmntsr.zip",
    "Tomb Raider 1.sh": "tomb.raider.1.zip",
    "tombraider1/": "tomb.raider.1.zip",
    "Ultimatetapankaikki.sh": "ultimatetapankaikki.zip",
    "ultimatetapankaikki/": "ultimatetapankaikki.zip",
    "Undertale.sh": "undertale.zip",
    "undertale/": "undertale.zip",
    "UQM.sh": "uqm.zip",
    "UQM/": "uqm.zip",
    "VanillaRA.sh": "vanillara.zip",
    "vanillara/": "vanillara.zip",
    "VanillaTD.sh": "vanillatd.zip",
    "vanillatd/": "vanillatd.zip",
    "VCMI.sh": "vcmi.zip",
    "vcmi/": "vcmi.zip",
    "VVVVVV.sh": "vvvvvv.zip",
    "VVVVVV/": "vvvvvv.zip",
    "Wetspot2.sh": "wetspot2.zip",
    "wetspot2/": "wetspot2.zip",
    "World War II GI.sh": "world.war.ii.gi.zip",
    "Worship Vector.sh": "worship_vector.zip",
    "worship/": "worship_vector.zip",
    "xrick/": "rick.dangerous.zip"
  },
  "ports": {
    "2048.zip": {
      "file": "2048/2048.port.json",
      "items": ["2048.sh", "2048/"],
      "name": "2048.zip"
    },
    "abes_adventure.zip": {
      "file": "abes_adventure/abes_adventure.port.json",
      "items": ["Abes Adventure.sh", "abes_adventure/"],
      "name": "abes_adventure.zip"
    },
    "abuse.zip": {
      "file": "Abuse/abuse.port.json",
      "items": ["Abuse/", "Abuse.sh"],
      "name": "abuse.zip"
    },
    "alephone-marathon.zip": {
      "file": "alephone/alephone-marathon.port.json",
      "items": ["alephone/", "Marathon.sh"],
      "name": "alephone-marathon.zip"
    },
    "alephone-marathon2.zip": {
      "file": "alephone/alephone-marathon2.port.json",
      "items": ["alephone/", "Marathon 2.sh"],
      "name": "alephone-marathon2.zip"
    },
    "alephone-marathoninfinity.zip": {
      "file": "alephone/alephone-marathoninfinity.port.json",
      "items": ["alephone/", "Marathon Infinity.sh"],
      "name": "alephone-marathoninfinity.zip"
    },
    "am2r.zip": {
      "file": "am2r/am2r.port.json",
      "items": ["am2r/", "AM2R.sh"],
      "name": "am2r.zip"
    },
    "anarch.zip": {
      "file": "anarch/anarch.port.json",
      "items": ["anarch/", "Anarch.sh"],
      "name": "anarch.zip"
    },
    "augustus.zip": {
      "file": "augustus/augustus.port.json",
      "items": ["Augustus.sh", "augustus/"],
      "name": "augustus.zip"
    },
    "avp.zip": {
      "file": "avp/avp.port.json",
      "items": ["Alien vs Predator.sh", "avp/"],
      "name": "avp.zip"
    },
    "axiom.verge.zip": {
      "file": "axiom-verge/axiom.verge.port.json",
      "items": ["axiom-verge/", "Axiom Verge.sh"],
      "name": "axiom.verge.zip"
    },
    "bbja.zip": {
      "file": "jukeboxadventure/bbja.port.json",
      "items": ["Blues Brothers Jukebox Adventure.sh", "jukeboxadventure/"],
      "name": "bbja.zip"
    },
    "bermuda_syndrome.zip": {
      "file": "bermuda/bermuda_syndrome.port.json",
      "items": ["bermuda/", "Bermuda Syndrome.sh"],
      "name": "bermuda_syndrome.zip"
    },
    "billyfrontier.zip": {
      "file": "billyfrontier/billyfrontier.port.json",
      "items": ["BillyFrontier.sh", "billyfrontier/"],
      "name": "billyfrontier.zip"
    },
    "blobby.volley2.zip": {
      "file": "blobbyvolley2/blobby.volley2.port.json",
      "items": ["Blobby Volley 2.sh", "blobbyvolley2/"],
      "name": "blobby.volley2.zip"
    },
    "blobwars.zip": {
      "file": "blobwars/blobwars.port.json",
      "items": ["Blobwars.sh", "blobwars/"],
      "name": "blobwars.zip"
    },
    "block.attack.zip": {
      "file": "blockattack/block.attack.port.json",
      "items": ["Block Attack.sh", "blockattack/"],
      "name": "block.attack.zip"
    },
    "blockout2.zip": {
      "file": "blockout2/blockout2.port.json",
      "items": ["Blockout 2.sh", "blockout2/"],
      "name": "blockout2.zip"
    },
    "blood.zip": {
      "file": "Blood/blood.port.json",
      "items": ["Blood.sh", "Blood/"],
      "name": "blood.zip"
    },
    "blues.brothers.zip": {
      "file": "bluesbrothers/blues.brothers.port.json",
      "items": ["Blues Brothers.sh", "bluesbrothers/"],
      "name": "blues.brothers.zip"
    },
    "bstone-aog.zip": {
      "file": "bstone-aog/bstone-aog.port.json",
      "items": ["Blake Stone - Aliens of Gold.sh", "bstone-aog/"],
      "name": "bstone-aog.zip"
    },
    "bstone-ps.zip": {
      "file": "bstone-ps/bstone-ps.port.json",
      "items": ["Blake Stone - Planet Strike.sh", "bstone-ps/"],
      "name": "bstone-ps.zip"
    },
    "bugdom.zip": {
      "file": "bugdom/bugdom.port.json",
      "items": ["Bugdom.sh", "bugdom/"],
      "name": "bugdom.zip"
    },
    "c-dogs.zip": {
      "file": "cdogs/c-dogs.port.json",
      "items": ["C-Dogs.sh", "cdogs/"],
      "name": "c-dogs.zip"
    },
    "cannonball.zip": {
      "file": "cannonball/cannonball.port.json",
      "items": ["Cannonball.sh", "cannonball/"],
      "name": "cannonball.zip"
    },
    "cave.story-evo.zip": {
      "file": "nxengine-evo/cave.story-evo.port.json",
      "items": ["Cave Story-evo.sh", "nxengine-evo/"],
      "name": "cave.story-evo.zip"
    },
    "cave.story.zip": {
      "file": "cavestory/cave.story.port.json",
      "items": ["Cave Story.sh", "cavestory/"],
      "name": "cave.story.zip"
    },
    "celeste.zip": {
      "file": "celeste/celeste.port.json",
      "items": ["Celeste.sh", "celeste/"],
      "name": "celeste.zip"
    },
    "commander.genius.zip": {
      "file": "cgenius/commander.genius.port.json",
      "items": ["cgenius/", "Commander Genius.sh"],
      "name": "commander.genius.zip"
    },
    "corsixth.zip": {
      "file": "CorsixTH/corsixth.port.json",
      "items": ["CorsixTH/", "CorsixTH.sh"],
      "name": "corsixth.zip"
    },
    "cosmo-engine.zip": {
      "file": "cosmo-engine/cosmo-engine.port.json",
      "items": ["cosmo-engine/", "Cosmos Cosmic Adventure.sh"],
      "name": "cosmo-engine.zip"
    },
    "cromagrally.zip": {
      "file": "cromagrally/cromagrally.port.json",
      "items": ["CroMagRally.sh", "cromagrally/"],
      "name": "cromagrally.zip"
    },
    "davegnukem.zip": {
      "file": "davegnukem/davegnukem.port.json",
      "items": ["Dave Gnukem.sh", "davegnukem/"],
      "name": "davegnukem.zip"
    },
    "derclou.zip": {
      "file": "derclou/derclou.port.json",
      "items": ["Der Clou.sh", "derclou/"],
      "name": "derclou.zip"
    },
    "devilutionx.zip": {
      "file": "devilution/devilutionx.port.json",
      "items": ["devilution/", "Devilutionx.sh"],
      "name": "devilutionx.zip"
    },
    "dinothawr.zip": {
      "file": "dinothawr/dinothawr.port.json",
      "items": ["Dinothawr.sh", "dinothawr/"],
      "name": "dinothawr.zip"
    },
    "diverdown.zip": {
      "file": "diverdown/diverdown.port.json",
      "items": ["DiverDown.sh", "diverdown/"],
      "name": "diverdown.zip"
    },
    "doom3.zip": {
      "file": "doom3/doom3.port.json",
      "items": ["Doom 3.sh", "doom3/"],
      "name": "doom3.zip"
    },
    "duke.nukem.3d.zip": {
      "file": "rednukem-dn3d-atomic/duke.nukem.3d.port.json",
      "items": ["Duke Nukem 3D.sh", "rednukem-dn3d-atomic/"],
      "name": "duke.nukem.3d.zip"
    },
    "dungeonrush.zip": {
      "file": "dungeonrush/dungeonrush.port.json",
      "items": ["dungeonrush/", "DungeonRush.sh"],
      "name": "dungeonrush.zip"
    },
    "enigma.zip": {
      "file": "enigma/enigma.port.json",
      "items": ["enigma/", "Enigma.sh"],
      "name": "enigma.zip"
    },
    "exhumed.zip": {
      "file": "Exhumed/exhumed.port.json",
      "items": ["Exhumed.sh", "Exhumed/"],
      "name": "exhumed.zip"
    },
    "exult.zip": {
      "file": "exult/exult.port.json",
      "items": ["exult/", "Exult-keyring.sh", "Exult-nokeyring.sh"],
      "name": "exult.zip"
    },
    "fade_to_black.zip": {
      "file": "f2bgl/fade_to_black.port.json",
      "items": ["f2bgl/", "F2bgl.sh"],
      "name": "fade_to_black.zip"
    },
    "falling_time.zip": {
      "file": "falling_time/falling_time.port.json",
      "items": ["Falling Time.sh", "falling_time/"],
      "name": "falling_time.zip"
    },
    "fallout1.zip": {
      "file": "fallout1/fallout1.port.json",
      "items": ["Fallout 1.sh", "fallout1/"],
      "name": "fallout1.zip"
    },
    "fallout2.zip": {
      "file": "fallout2/fallout2.port.json",
      "items": ["Fallout 2.sh", "fallout2/"],
      "name": "fallout2.zip"
    },
    "fheroes2.zip": {
      "file": "fheroes2/fheroes2.port.json",
      "items": ["fheroes2/", "Fheroes2.sh"],
      "name": "fheroes2.zip"
    },
    "flare.zip": {
      "file": "flare/flare.port.json",
      "items": ["Flare Engine.sh", "flare/"],
      "name": "flare.zip"
    },
    "freedom.planet.zip": {
      "file": "freedomplanet/freedom.planet.port.json",
      "items": ["Freedom Planet.sh", "freedomplanet/"],
      "name": "freedom.planet.zip"
    },
    "freedroid.zip": {
      "file": "freedroid/freedroid.port.json",
      "items": ["Freedroid.sh", "freedroid/"],
      "name": "freedroid.zip"
    },
    "freegemas.zip": {
      "file": "freegemas/freegemas.port.json",
      "items": ["freegemas/", "Freegemas.sh"],
      "name": "freegemas.zip"
    },
    "freeserf.zip": {
      "file": "freeserf/freeserf.port.json",
      "items": ["FreeSerf.sh", "freeserf/"],
      "name": "freeserf.zip"
    },
    "gemrb.zip": {
      "file": "gemrb/gemrb.port.json",
      "items": ["GemRB.sh", "gemrb/"],
      "name": "gemrb.zip"
    },
    "gigalomania.zip": {
      "file": "gigalomania/gigalomania.port.json",
      "items": ["Gigalomania.sh", "gigalomania/"],
      "name": "gigalomania.zip"
    },
    "half-life.2.zip": {
      "file": "halflife2/half-life.2.port.json",
      "items": ["Half-Life 2.sh", "halflife2/"],
      "name": "half-life.2.zip"
    },
    "half-life.zip": {
      "file": "Half-Life/half-life.port.json",
      "items": ["Half-Life.sh", "Half-Life/"],
      "items_opt": ["Half-Life Blue Shift.sh", "Half-Life Opposing Forces.sh"],
      "name": "half-life.zip"
    },
    "heart.of.darkness.zip": {
      "file": "hode/heart.of.darkness.port.json",
      "items": ["Heart of Darkness.sh", "hode/"],
      "name": "heart.of.darkness.zip"
    },
    "hex-a-hop.zip": {
      "file": "hex-a-hop/hex-a-hop.port.json",
      "items": ["Hex-A-Hop.sh", "hex-a-hop/"],
      "name": "hex-a-hop.zip"
    },
    "hexen2.zip": {
      "file": "hexen2/hexen2.port.json",
      "items": ["Hexen 2 - Portal of Praevus.sh", "Hexen 2.sh", "hexen2/"],
      "name": "hexen2.zip"
    },
    "hijinx.zip": {
      "file": "hijinx/hijinx.port.json",
      "items": ["Hijinx.sh", "hijinx/"],
      "name": "hijinx.zip"
    },
    "hocoslamfy.zip": {
      "file": "hocoslamfy/hocoslamfy.port.json",
      "items": ["Hocoslamfy.sh", "hocoslamfy/"],
      "name": "hocoslamfy.zip"
    },
    "hurrican.zip": {
      "file": "hurrican/hurrican.port.json",
      "items": ["hurrican/", "Hurrican.sh"],
      "name": "hurrican.zip"
    },
    "hydra.castle.labyrinth.zip": {
      "file": "hcl/hydra.castle.labyrinth.port.json",
      "items": ["hcl/", "Hydra Castle Labyrinth.sh"],
      "name": "hydra.castle.labyrinth.zip"
    },
    "iconoclasts.zip": {
      "file": "iconoclasts/iconoclasts.port.json",
      "items": ["iconoclasts/", "Iconoclasts.sh"],
      "name": "iconoclasts.zip"
    },
    "iichantra_pear.zip": {
      "file": "iichantra_pear/iichantra_pear.port.json",
      "items": ["IIChantra P.E.A.R.sh", "iichantra_pear/"],
      "name": "iichantra_pear.zip"
    },
    "invaders.zip": {
      "file": "Invaders/invaders.port.json",
      "items": ["Invaders.sh", "Invaders/"],
      "name": "invaders.zip"
    },
    "iortcw.zip": {
      "file": "iortcw/iortcw.port.json",
      "items": ["iortcw/", "Return to Castle Wolfenstein.sh"],
      "name": "iortcw.zip"
    },
    "jediacademy.zip": {
      "file": "JediAcademy/jediacademy.port.json",
      "items": ["JediAcademy/", "Star Wars Jedi Knight - Jedi Academy.sh"],
      "name": "jediacademy.zip"
    },
    "jedioutcast.zip": {
      "file": "JediOutcast/jedioutcast.port.json",
      "items": ["JediOutcast/", "Star Wars Jedi Knight II - Jedi Outcast.sh"],
      "name": "jedioutcast.zip"
    },
    "maldita.castilla.zip": {
      "file": "MalditaCastilla/maldita.castilla.port.json",
      "items": ["Maldita Castilla.sh", "MalditaCastilla/"],
      "name": "maldita.castilla.zip"
    },
    "meritous.zip": {
      "file": "meritous/meritous.port.json",
      "items": ["Meritous.sh", "meritous/"],
      "name": "meritous.zip"
    },
    "mightymike.zip": {
      "file": "mightymike/mightymike.port.json",
      "items": ["MightyMike.sh", "mightymike/"],
      "name": "mightymike.zip"
    },
    "mirrormagic.zip": {
      "file": "mirrormagic/mirrormagic.port.json",
      "items": ["Mirror Magic.sh", "mirrormagic/"],
      "name": "mirrormagic.zip"
    },
    "moonlight.zip": {
      "file": "moonlight/moonlight.port.json",
      "items": ["moonlight/", "Moonlight.sh"],
      "name": "moonlight.zip"
    },
    "mr.boom.zip": {
      "file": "mrboom/mr.port.json",
      "items": ["Mr. Boom.sh", "mrboom/"],
      "name": "mr.boom.zip"
    },
    "multris.zip": {
      "file": "multris/multris.port.json",
      "items": ["multris/", "Multris.sh"],
      "name": "multris.zip"
    },
    "nam.zip": {
      "file": "rednukem-NAM/nam.port.json",
      "items": ["NAM.sh", "rednukem-NAM/"],
      "name": "nam.zip"
    },
    "nanosaur.zip": {
      "file": "nanosaur/nanosaur.port.json",
      "items": ["Nanosaur.sh", "nanosaur/"],
      "name": "nanosaur.zip"
    },
    "neverball.zip": {
      "file": "neverball/neverball.port.json",
      "items": ["neverball/", "Neverball.sh", "Neverputt.sh"],
      "name": "neverball.zip"
    },
    "nkaruga.zip": {
      "file": "nkaruga/nkaruga.port.json",
      "items": ["nkaruga/", "nKaruga.sh"],
      "name": "nkaruga.zip"
    },
    "oddworld.zip": {
      "file": "relive/oddworld.port.json",
      "items": ["Oddworld Abes Oddysee.sh", "Oddworld Abes Exoddus.sh", "relive/"],
      "name": "oddworld.zip"
    },
    "openblok.zip": {
      "file": "openblok/openblok.port.json",
      "items": ["openblok/", "OpenBlok.sh"],
      "name": "openblok.zip"
    },
    "openclaw.zip": {
      "file": "openclaw/openclaw.port.json",
      "items": ["Openclaw.sh", "openclaw/"],
      "name": "openclaw.zip"
    },
    "openfodder.zip": {
      "file": "openfodder/openfodder.port.json",
      "items": ["OpenFodder.sh", "openfodder/"],
      "name": "openfodder.zip"
    },
    "openjazz.zip": {
      "file": "openjazz/openjazz.port.json",
      "items": ["openjazz/", "OpenJazz.sh"],
      "name": "openjazz.zip"
    },
    "openomf.zip": {
      "file": "openomf/openomf.port.json",
      "items": ["openomf/", "Openomf.sh"],
      "name": "openomf.zip"
    },
    "openrct2.zip": {
      "file": "openrct2/openrct2.port.json",
      "items": ["OpenRCT2.sh", "openrct2/"],
      "name": "openrct2.zip"
    },
    "openttd.zip": {
      "file": "openttd/openttd.port.json",
      "items": ["openttd/", "Openttd.sh"],
      "name": "openttd.zip"
    },
    "opentyrian.zip": {
      "file": "opentyrian/opentyrian.port.json",
      "items": ["OpenTyrian.sh", "opentyrian/"],
      "name": "opentyrian.zip"
    },
    "openxcom.zip": {
      "file": "openxcom/openxcom.port.json",
      "items": ["openxcom/", "OpenXcomEX.sh"],
      "name": "openxcom.zip"
    },
    "ottomatic.zip": {
      "file": "ottomatic/ottomatic.port.json",
      "items": ["OttoMatic.sh", "ottomatic/"],
      "name": "ottomatic.zip"
    },
    "owlboy.zip": {
      "file": "owlboy/owlboy.port.json",
      "items": ["owlboy/", "Owlboy.sh"],
      "name": "owlboy.zip"
    },
    "pekka-kana-2.zip": {
      "file": "pekka-kana-2/pekka-kana-2.port.json",
      "items": ["Pekka Kana 2.sh", "pekka-kana-2/"],
      "name": "pekka-kana-2.zip"
    },
    "powder.zip": {
      "file": "powder/powder.port.json",
      "items": ["Powder.sh", "powder/"],
      "name": "powder.zip"
    },
    "prehistorik.2.zip": {
      "file": "prehistorik2/prehistorik.2.port.json",
      "items": ["Prehistorik 2.sh", "prehistorik2/"],
      "name": "prehistorik.2.zip"
    },
    "profadeluxe.zip": {
      "file": "profadeluxe/profadeluxe.port.json",
      "items": ["Abu Simbel Profanation Deluxe.sh", "profadeluxe/"],
      "name": "profadeluxe.zip"
    },
    "quake.2.zip": {
      "file": "quake2/quake.2.port.json",
      "items": ["Quake 2.sh", "quake2/"],
      "name": "quake.2.zip"
    },
    "quake.zip": {
      "file": "quake/quake.port.json",
      "items": ["quake/", "Quake.sh"],
      "name": "quake.zip"
    },
    "quake3.zip": {
      "file": "quake3/quake3.port.json",
      "items": ["Quake 3.sh", "quake3/"],
      "name": "quake3.zip"
    },
    "rawgl.zip": {
      "file": "rawgl/rawgl.port.json",
      "items": ["RAWGL.sh", "rawgl/"],
      "name": "rawgl.zip"
    },
    "redneck.rampage.rides.again.zip": {
      "file": "rednukem-redneck2/redneck.rampage.rides.again.port.json",
      "items": ["Redneck Rampage Rides Again.sh", "rednukem-redneck2/"],
      "name": "redneck.rampage.rides.again.zip"
    },
    "redneck.rampage.zip": {
      "file": "rednukem-redneck1/redneck.rampage.port.json",
      "items": ["Redneck Rampage.sh", "rednukem-redneck1/"],
      "name": "redneck.rampage.zip"
    },
    "reminiscence.zip": {
      "file": "reminiscence/reminiscence.port.json",
      "items": ["reminiscence/", "REminiscence.sh"],
      "name": "reminiscence.zip"
    },
    "ri_li.zip": {
      "file": "ri_li/ri_li.port.json",
      "items": ["Ri-Li.sh", "ri_li/"],
      "name": "ri_li.zip"
    },
    "rick.dangerous.zip": {
      "file": "xrick/rick.dangerous.port.json",
      "items": ["Rick Dangerous.sh", "xrick/"],
      "name": "rick.dangerous.zip"
    },
    "rigelengine.zip": {
      "file": "RigelEngine/rigelengine.port.json",
      "items": ["RigelEngine/", "RigelEngine.sh"],
      "name": "rigelengine.zip"
    },
    "rlvm.zip": {
      "file": "rlvm/rlvm.port.json",
      "items": ["Rlvm.sh", "rlvm/"],
      "name": "rlvm.zip"
    },
    "rocksndiamonds.zip": {
      "file": "rocksndiamonds/rocksndiamonds.port.json",
      "items": ["Rocks n Diamonds.sh", "rocksndiamonds/"],
      "name": "rocksndiamonds.zip"
    },
    "rott.zip": {
      "file": "rott/rott.port.json",
      "items": ["rott/", "ROTT.sh"],
      "name": "rott.zip"
    },
    "rvgl.zip": {
      "file": "rvgl/rvgl.port.json",
      "items": ["rvgl/", "RVGL.sh"],
      "name": "rvgl.zip"
    },
    "sdlpop.zip": {
      "file": "sdlpop/sdlpop.port.json",
      "items": ["sdlpop/", "SDLPoP.sh"],
      "name": "sdlpop.zip"
    },
    "shadow.warrior.zip": {
      "file": "shadow-warrior/shadow.warrior.port.json",
      "items": ["Shadow Warrior.sh", "shadow-warrior/"],
      "name": "shadow.warrior.zip"
    },
    "shipwreck.zip": {
      "file": "shipwreck/shipwreck.port.json",
      "items": ["shipwreck/", "Shipwreck.sh"],
      "name": "shipwreck.zip"
    },
    "shovel.knight.zip": {
      "file": "shovelknight/shovel.knight.port.json",
      "items": ["Shovel Knight.sh", "shovelknight/"],
      "name": "shovel.knight.zip"
    },
    "simplesokoban.zip": {
      "file": "simplesok/simplesokoban.port.json",
      "items": ["Simple Sokoban.sh", "simplesok/"],
      "name": "simplesokoban.zip"
    },
    "skijump3.zip": {
      "file": "skijump3/skijump3.port.json",
      "items": ["skijump3/", "Skijump3.sh"],
      "name": "skijump3.zip"
    },
    "sm64.zip": {
      "file": "sm64/sm64.port.json",
      "items": ["sm64.sh", "sm64/"],
      "name": "sm64.zip"
    },
    "sonic.1.zip": {
      "file": "sonic1/sonic.1.port.json",
      "items": ["Sonic 1.sh", "sonic1/"],
      "name": "sonic.1.zip"
    },
    "sonic.2.zip": {
      "file": "sonic2/sonic.2.port.json",
      "items": ["Sonic 2.sh", "sonic2/"],
      "name": "sonic.2.zip"
    },
    "sonic.cd.zip": {
      "file": "soniccd/sonic.cd.port.json",
      "items": ["Sonic CD.sh", "soniccd/"],
      "name": "sonic.cd.zip"
    },
    "sonic.mania.zip": {
      "file": "sonicmania/sonic.mania.port.json",
      "items": ["Sonic Mania.sh", "sonicmania/"],
      "name": "sonic.mania.zip"
    },
    "sorr.zip": {
      "file": "sorr/sorr.port.json",
      "items": ["sorr/", "SorR.sh"],
      "name": "sorr.zip"
    },
    "space.cadet.pinball.zip": {
      "file": "spacecadetpinball/space.cadet.pinball.port.json",
      "items": ["Space Cadet Pinball.sh", "spacecadetpinball/"],
      "name": "space.cadet.pinball.zip"
    },
    "spelunky.zip": {
      "file": "spelunky/spelunky.port.json",
      "items": ["spelunky/", "Spelunky.sh"],
      "name": "spelunky.zip"
    },
    "srb2.zip": {
      "file": "SRB2/srb2.port.json",
      "items": ["SRB2/", "SRB2.sh"],
      "name": "srb2.zip"
    },
    "srb2kart.zip": {
      "file": "srb2kart/srb2kart.port.json",
      "items": ["Sonic Robo Blast 2 Kart.sh", "srb2kart/"],
      "name": "srb2kart.zip"
    },
    "starcatcher.zip": {
      "file": "starcatcher/starcatcher.port.json",
      "items": ["Starcatcher.sh", "starcatcher/"],
      "name": "starcatcher.zip"
    },
    "stardewvalley.zip": {
      "file": "stardewvalley/stardewvalley.port.json",
      "items": ["stardewvalley/", "StardewValley.sh"],
      "name": "stardewvalley.zip"
    },
    "steelassault.zip": {
      "file": "steelassault/steelassault.port.json",
      "items": ["steelassault/", "SteelAssault.sh"],
      "name": "steelassault.zip"
    },
    "super.mario.war.zip": {
      "file": "smw/super.mario.war.port.json",
      "items": ["smw/", "Super Mario War.sh"],
      "name": "super.mario.war.zip"
    },
    "supertux.zip": {
      "file": "supertux/supertux.port.json",
      "items": ["supertux/", "SuperTux.sh"],
      "name": "supertux.zip"
    },
    "tamatool.zip": {
      "file": "tamatool/tamatool.port.json",
      "items": ["tamatool/", "Tamatool.sh"],
      "name": "tamatool.zip"
    },
    "tileworld.zip": {
      "file": "tileworld/tileworld.port.json",
      "items": [
        "Tile World (Chip's Challenge).sh",
        "Tile World (Natural Theme Mod).sh",
        "tileworld/"
      ],
      "name": "tileworld.zip"
    },
    "timespinner.zip": {
      "file": "timespinner/timespinner.port.json",
      "items": ["timespinner/", "Timespinner.sh"],
      "name": "timespinner.zip"
    },
    "tiny-crate.zip": {
      "file": "tiny-crate/tiny-crate.port.json",
      "items": ["Tiny Crate.sh", "tiny-crate/"],
      "name": "tiny-crate.zip"
    },
    "titan_tactics.zip": {
      "file": "titan_tactics/titan_tactics.port.json",
      "items": ["Titan Tactics.sh", "titan_tactics/"],
      "name": "titan_tactics.zip"
    },
    "tmntsr.zip": {
      "file": "tmntsr/tmntsr.port.json",
      "items": ["TMNTShreddersRevenge.sh", "tmntsr/"],
      "name": "tmntsr.zip"
    },
    "tomb.raider.1.zip": {
      "file": "tombraider1/tomb.raider.1.port.json",
      "items": ["Tomb Raider 1.sh", "tombraider1/"],
      "name": "tomb.raider.1.zip"
    },
    "ultimatetapankaikki.zip": {
      "file": "ultimatetapankaikki/ultimatetapankaikki.port.json",
      "items": ["Ultimatetapankaikki.sh", "ultimatetapankaikki/"],
      "name": "ultimatetapankaikki.zip"
    },
    "undertale.zip": {
      "file": "undertale/undertale.port.json",
      "items": ["undertale/", "Undertale.sh"],
      "name": "undertale.zip"
    },
    "uqm.zip": {
      "file": "UQM/uqm.port.json",
      "items": ["UQM/", "UQM.sh"],
      "name": "uqm.zip"
    },
    "vanillara.zip": {
      "file": "vanillara/vanillara.port.json",
      "items": ["VanillaRA.sh", "vanillara/"],
      "name": "vanillara.zip"
    },
    "vanillatd.zip": {
      "file": "vanillatd/vanillatd.port.json",
      "items": ["VanillaTD.sh", "vanillatd/"],
      "name": "vanillatd.zip"
    },
    "vcmi.zip": {
      "file": "vcmi/vcmi.port.json",
      "items": ["VCMI.sh", "vcmi/"],
      "name": "vcmi.zip"
    },
    "vvvvvv.zip": {
      "file": "VVVVVV/vvvvvv.port.json",
      "items": ["VVVVVV/", "VVVVVV.sh"],
      "name": "vvvvvv.zip"
    },
    "wetspot2.zip": {
      "file": "wetspot2/wetspot2.port.json",
      "items": ["Wetspot2.sh", "wetspot2/"],
      "name": "wetspot2.zip"
    },
    "world.war.ii.gi.zip": {
      "file": "rednukem-WWII/world.war.ii.gi.port.json",
      "items": ["rednukem-WWII/", "World War II GI.sh"],
      "name": "world.war.ii.gi.zip"
    },
    "worship_vector.zip": {
      "file": "worship/worship_vector.port.json",
      "items": ["Worship Vector.sh", "worship/"],
      "name": "worship_vector.zip"
    }
  }
}
